### ISSUE TITLE
debug_shellcode closes process immediately

### ISSUE THREAD

**Issue by wangray** [Gallopsled/pwntools#1054]
When I use `debug_shellcode`, pwntools opens a new terminal and makes the connection to the gdbserver, but then returns immediately and closes the process before I get a chance to interact with gdb. I need to add a `time.sleep()` after `debug_shellcode` to be able to use it. 

Here's an example to try (reading flag.txt) : 

```
shellcode = ''
shellcode += asm('lea rdi, [rip]')
shellcode += asm('add rdi, 51')
shellcode += asm('mov rax, 2')
shellcode += asm('syscall')
shellcode += asm('mov rsi, rdi')
shellcode += asm('mov rdi, rax')
shellcode += asm('mov rdx, 10')
shellcode += asm('mov rax, 0')
shellcode += asm('syscall')
shellcode += asm('mov rax, 1')
shellcode += asm('mov rdi, 0')
shellcode += asm('syscall')
shellcode += "flag.txt" + "\x00"

gdb.debug_shellcode(shellcode, '''
set disassembly-flavor intel
set height 0
b *0x6000b0
''')

# Without this, process closes immediately
time.sleep(10000)
```

**Comment by zachriggle** [comment]
Yes, as one would expect it to do.  It created the `process`, and attached the debugger -- then your Python script exited, and all of the processes created are cleaned up.

I expect you want to do something like:

```py
io = gdb.debug_shellcode(...)
io.interactive()
```

For what it's worth, you can also probably save some time by just doing:

```
shellcraft.cat('flag.txt')
```

Instead of hand-rolling your own shellcode.

Finally, you're using `debug_shellcode` wrong.  `debug_shellcode` is for assembled shellcode -- not assembly itself.  You need to call `asm()` first, or use `debug_assembly`.
