### ISSUE TITLE
Got some trouble while translating document for pwntools using readthedocs

### ISSUE THREAD

**Issue by WangYihang** [Gallopsled/pwntools#1091]
Hi, bro
I want to translate the document for pwntools from English to chinses
but I wonder how can I make it more comply with your standard

I just try to use `readthedocs`.
First step, I fork this repo
Second, import a repo on `readthedocs`
Then the website will auto-compile the docs from rst file to HTML file
but failed, the error report is:
![fireshot capture 9 - pwntools-docs-zh i read the docs_ - https___readthedocs org_projects_pw](https://user-images.githubusercontent.com/16917636/34468511-6713f4ae-ef45-11e7-87eb-d6878540fe65.png)

I have tried a lot of times, some time the error says:
```
no such file: conf.py
```

Could you tell me how should I do to make it works, thank you so much

English is not my native language, forgive my poor english, thank you
best

**Comment by zachriggle** [comment]
You need to change some settings on ReadTheDocs.

When you have your translations up, let me know and I can link to it.

Since there's not a good way to "export" the settings that you can re-import them, I took some screenshots.

<img width="898" alt="screen shot 2018-01-02 at 11 21 25 am" src="https://user-images.githubusercontent.com/111640/34492923-2933373e-efaf-11e7-8fe0-fa489ee28fe0.png">

<img width="992" alt="screen shot 2018-01-02 at 11 20 36 am" src="https://user-images.githubusercontent.com/111640/34492925-2ca1590a-efaf-11e7-92c9-d95bc00d672c.png">

<img width="645" alt="screen shot 2018-01-02 at 11 20 43 am" src="https://user-images.githubusercontent.com/111640/34492930-3154b546-efaf-11e7-8e0f-653cf75ea90a.png">

**Comment by zachriggle** [comment]
Separately, it might be worth using the internationalization (i18n) tools built into Sphinx, which we use for documentation.

http://www.sphinx-doc.org/en/stable/intl.html

This will also make it easier for future translations.

**Comment by WangYihang** [comment]
@zachriggle Cool, bro
thank you for general help, I'll let you know about my progress
thank you so much again

**Comment by WangYihang** [comment]
Thank god, according to your configuration, succeed this time. thank you, this issue can be closed, thank you

**Comment by zachriggle** [comment]
Can you link to your translation?

**Comment by WangYihang** [comment]
@zachriggle 
> https://readthedocs.org/projects/pwntools-docs-zh/

**Comment by CHYbeta** [comment]
https://github.com/Magic-Translater/Pwntools.Doc.In.Zh-cn

**Comment by WangYihang** [comment]
Cool, thank you for suggestion, I checked the translation which you
commented just now
Maybe we are doing the same thing cus that project is not finished yet,
but we can learn lot while translating this doc
We can communicate with each other, so we can make it better ,right?
Thank you again.
chybeta <notifications@github.com>于2018年1月4日 周四上午7:40写道：

**Comment by zachriggle** [comment]
You need to set the language of your project, it's still marked as `en`.

<img width="603" alt="screen shot 2018-01-04 at 3 23 16 pm" src="https://user-images.githubusercontent.com/111640/34584918-3db8b5b6-f163-11e7-970b-2f114cf89436.png">

**Comment by WangYihang** [comment]
got it, the language of this project is set to Simplified Chinese
Sorry to trouble you, thank you
@zachriggle
