### ISSUE TITLE
Travis tests are broken

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1112]
Looks like tests broke somehow.  

We didn't change anything that would cause this, something in the dependency / testing stack changed.

Good: https://travis-ci.org/Gallopsled/pwntools/builds/338641937
Bad: https://travis-ci.org/Gallopsled/pwntools/builds/341197032

Error message:
```
$ PWNLIB_NOTERM=1 coverage run -m sphinx -b doctest docs/source docs/build/doctest
Running Sphinx v1.7.0
Extension error:
Could not import extension pwnlib.internal.dochelper (exception: No module named compat)
Coverage.py warning: Module ~/.pwntools-cache/ was never imported. (module-not-imported)
The command "PWNLIB_NOTERM=1 coverage run -m sphinx -b doctest docs/source docs/build/doctest" exited with 2.
```

Separately, we should probably have something that auto-files a bug when tests break.

**Comment by zachriggle** [comment]
@Idolf this will likely block the next release

**Comment by Arusekk** [comment]
Actually, it is still failing. It turns out that the hotfix here does not do its job:
https://github.com/Gallopsled/pwntools/blob/d67cb152ed95f8694c262db028ec5f4183ca14fd/docs/source/conf.py#L43-L46
So the solution would be to find where else the problematic import resides.

One thing is that the `docs/requirements.txt` file is requiring an old version of `sphinxcontrib-autoprogram`, which still has the wrong import (newest is `0.1.4`, not `0.1.2`):
https://github.com/Gallopsled/pwntools/blob/d67cb152ed95f8694c262db028ec5f4183ca14fd/docs/requirements.txt#L2
And the other old import is in `pwnlib/internal/dochelper.py`:
https://github.com/Gallopsled/pwntools/blob/d67cb152ed95f8694c262db028ec5f4183ca14fd/pwnlib/internal/dochelper.py#L6
