### ISSUE TITLE
Investigate LIEF project for ELF / PE / MachO parsing

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1147]
This looks pretty interesting! 

https://lief-project.github.io/doc/latest/Intro.html

**Comment by zachriggle** [comment]
Closing this out since there's been no progress.

**Comment by zachriggle** [comment]
This is still something that would be really nice :(

**Comment by jt0dd** [comment]
Could we use https://github.com/qilingframework/qiling toward this goal? I seem to be able to retrieve the equivalent of a core dump after exploiting a PE file through this framework. Unfortunately, due to Windows licensing issues, it can't include System32 by default and instead requires a script running to pull those contents into the context of the framework for use. I suppose that poses a potentially non-circumventable challenge.

**Comment by jt0dd** [comment]
Any progress on this? It's sad that such a powerful library is so limited against Portable Executables, which make up a lion-share of software in virtually every industry.
