### ISSUE TITLE
Can I use images?

### ISSUE THREAD

**Issue by reasley-com** [Gallopsled/pwntools#1246]
s

**Comment by zachriggle** [comment]
I would recommend consulting the [Pwntools license](https://github.com/Gallopsled/pwntools/blob/dev/LICENSE-pwntools.txt)

Which image(s) are you referring to?

Also, I'm curious about the book that you're writing, Pwntools' inclusion, etc.  Would you mind elaborating more?

**Comment by reasley-com** [comment]
I'm trying to write a protostar problem solver, but I wanted to use the logo.png file at https://github.com/Gallopsled/pwntools while briefly using pwntools.​
And I checked the site that I sent, and it says ok even if I use it for commercial purpose. Can I tell you exactly what I recognized? 
-----Original Message-----

**Comment by Arusekk** [comment]
I have no idea, since the logo was not made by me, nor do I know who created it or how is it licensed. I guess (do not trust me) that using a product's logo for advertising its features is universally fine? Anyway, I would do so, but don't trust me ;)

Closing this, since it is a little bit off-topic and quite old, and you have probably already made your choice anyway.

**Comment by zachriggle** [comment]
I'm also fine with you using the Pwntools logo, as long as it's not for anything malicious!
