### ISSUE TITLE
Next release, `dev3` merged to `dev` and promoted to `beta`

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1276]
We need to cut a new release so that @Arusekk's work to get everything Python3-compatible (and Python2-compatible!!) can be used and is the primary development branch.

We used to have a regular 6-week release cadence (dev => beta => stable), but this fell to the wayside due to lack of free time on my part.

Since this is NOT a backward-compatibility-breaking change, SemVer would tell us not to bump the major version, but I think it's a useful delineation point and worth the bump because of Python3 support.

Do we have any concerns about `v3.14` version being re-named to `v4.0`?

No new branches are needed, no name changes -- support will simply roll off in the same cadence that we already do.

My plan is:

0. Implement #1253 such that there is a new top-level module `pwntools` that is more or less an alias to `pwn`.  More information is on that issue, but I'd like the cosmetic changes (`from pwn` => `from pwntools` and `v3` => `v4`) to be together.
1. Do whatever merges are necessary between `dev` and `dev3` to bring them into sync
2. Delete the `dev3` branch.  All future `dev` pull requests MUST pass CI for Python2 and Python3.
3. Promote the bi-compatible `dev` branch to `beta`
4. Tag `beta` as `4.0.0-beta` (instead of `3.14-beta`)
5. Everything else release-wise works as normal

Pwntools `v3.13` will be the last release in the 3.x series.

**Comment by Anutrix** [comment]
Any updates?

**Comment by zachriggle** [comment]
I can't contribute to Pwntools due to my employer's restrictions on open-source contributions.  I've made @Arusekk an Administrator of the Pwntools repository, any future merges / releases will be through him.  I can only provide comments / help / suggestions, no code or commits.

**Comment by Arusekk** [comment]
@zachriggle What is the status on this?

My idea is to promote something to stable (maybe current dev), then current dev3 to beta, and release them both on PyPI, since there have been no updates for quite a long time.

EDIT: It's been over half a year since last release.

**Comment by zachriggle** [comment]
@Arusekk my hands are tied and I am unable to contribute code.  I fully support you performing the merges, and can help you out out-of-band.  @TethysSvensson is the person who used to do merges and releases, he may be able to help more.  See #915 for more information

**Comment by TethysSvensson** [comment]
## Release process

The release process I followed was this:

1. Make sure that the branches look like we want them to before the begin doing a release.
    * Are there any outstanding PRs we would like merged before the release is done?
    * Are all of my local branches are up to date?
        * `for b in stable beta dev; do git checkout $b; git pull --ff-only origin $b; done`
    * Have we maintained the correct relationship between the branches?
        * If we have done proper branch maintainence, then `stable` can always be fast-forwarded into `beta` and `beta` into `dev`. While this **should** always be true, in practice we often forget to e.g. merge fixes from stable into beta.
        * Before we begin, we make sure to fix any such mistakes. If there were no mistakes, these commands will do nothing.
        * `git checkout beta && git merge stable && git push origin beta`
        * `git checkout dev && git merge beta && git push origin dev`

2. I created the new stable release. I had a reminder file for this step, and I did stuff by hand by copy pasting from it. It could probably be automated, but I never had the time. The reminder file is at the end of this section.
3. I created the new beta release. I used the same file as in step 2, but with `OLD_BRANCH=beta`, `CUR_BRANCH=dev` and `RELEASE_VERSION` should be of the form `3.X.0betaY` instead of `3.X.Y`.
4. At this point, I had created new `stable` and `beta` commits, but the `dev` branch was still missing a new version number on `dev`. I bumped the version numbers on `dev`, created a new commit and pushed it to the `dev` branch.
5. I created releases on the github website by clicking on some buttons in my browser. Ideally they would contain information from the `CHANGELOG.md`, but sometimes I was too lazy to include it.
6. I changed the topic in the irc `#pwntools` channel and wrote a small message there. I sometimes also wrote on `#gallopsled`.
7. I sometimes wrote a message on our twitter channel.

Below is a cleaned up version of my reminder file. Note that some of the steps were very loosely specified in my original file, since I only used it as a reminder. I have tried to be more explicit here, but that means that I might have introduced a few inaccuracies/bugs in some of the commands. Please read through instead of following it blindly.

```
CUR_BRANCH=beta
OLD_BRANCH=stable
RELEASE_VERSION=3.X.Y # Use the actual version number here
git checkout $CUR_BRANCH

# Clean up any existing pwntools installations quite thoroughly
sudo rm -rf /usr/local/lib/python2.7/dist-packages/pwntools*
sudo rm -rf /usr/local/lib/python2.7/dist-packages/pwnlib*
sudo sed -i '/pwntools/d' /usr/local/lib/python2.7/dist-packages/easy-install.pth

# Clean up git repo status
sudo rm -rf *.egg-info dist
git clean -fxd  -q

# See that the current pwntools on pypi can still install and uninstall cleanly
sudo -H pip install -q pwntools
sudo -H pip uninstall -q -y pwntools
shellcraft # This should now give an error, because of the uninstall

# Create package
sudo python setup.py sdist

# Test that install+uninstall+install works as expected, since we have broken it before
sudo -H pip install -q dist/* # There is only a single file
sudo -H pip uninstall -q -y pwntools
sudo -H pip install -q dist/* # There is only a single file

# Test that the installation actually works as expected
shellcraft # should not give an error
shellcraft amd64.linux.connect test.com 1337 -f asm
head -c 128 /bin/sh | phd
# Run a few times to look for regressions compared to previous import times
# As far as I remember this should be about 200 ms after having warmed up
time python -c 'import pwn'
time python -c 'import pwn'
time python -c 'import pwn'
time python -c 'import pwn'

# Clean up again
sudo -H pip uninstall -q -y pwntools

# When doing this in step 2, it will do nothing
# When doing this in step 3, it will add the release commit done in step 2
# as a parent of the release commit we are about to do. This is both to make
# easier for myself (so that I do not need to edit CHANGELOG.md and README.md again)
# but also needed to retain the invariant that stable can always be fast-forwared
# to beta
git merge --no-commit $OLD_BRANCH

# Update version information
# Note for README.md:
#   Just after a release, this file should be the same on all branches.
#   It should contain the stable version number.
# Note for CHANGELOG.md:
#   Just after a release, this file should be the same on all branches.
#   It should contain the latest known changelog information for all branches.
vim setup.py pwnlib/version.py CHANGELOG.md README.md
git add setup.py pwnlib/version.py CHANGELOG.md README.md

git add setup.py pwnlib/version.py CHANGELOG.md README.md
git commit -m "Release $RELEASE_VERSION"
git tag $RELEASE_VERSION
git checkout $OLD_BRANCH
git merge --ff-only $CUR_BRANCH

# Push the release to github and upload to pypi
git push origin $CUR_BRANCH --tags
sudo python setup.py -q sdist upload
```

## Example runthrough
To get a feeling for how this worked in practice, let us look at how I did the releases `3.9.0` and `3.10.0beta0`, including creating the initial commit for `3.11.0dev`.

To follow along at home, I strongly recommend looking at `git log --graph --oneline b62804ef ^267c6cc1^@ ^1a94acab^@`. This will show both the world as it looked like before the releases as well as any commits we are about to "create" in our walk-through.

### Before starting the process

Before beginning on step 1, world looked like this:

* `stable` was at `267c6cc1 Force Ubuntu 12.04 until we can migrate to 14.04 (#1023)`
* `beta` was at `1a94acab (tag: 3.9.0beta0) Release 3.9.0beta0`
* `dev` was at `5831796f Add configurable gdbinit (#1007)`

### Step 1

I created two merge commits.

Afterwards the world looked like this:

* `stable` did not change.
* `beta` was updated to `3e163e9c Merge branch 'stable' into beta`. The commit is a merge and it's parents were the stable and beta branches.
* `dev` was updated to `7cd3c7b3 Merge branch 'beta' into dev`. The commit is a merge and it's parents were the beta and dev branches (including the just created merge commit).

### Step 2

I created the `3.9.0` release as commit `92ad1a49`, which also has the tag `3.9.0`. It has a single parent commit, the beta branch (since stable is already contained in beta). Try doing a `git show 92ad1a49` to see what I changed in `README.md`, `CHANGELOG.md`, `setup.py` and `pwnlib/version.py`.

Afterwards the world looked like this:

* `stable` was at `92ad1a49 (tag: 3.9.0) Release 3.9.0`.
* `beta` was also at `92ad1a49`.
* `dev` did not change.

### Step 3

I created the `3.10.0beta0` release as commit `ec98dc12`, which also has the tag `3.10.0beta0`. It has two parents commits, the dev and beta branches. Try doing a `git show ec98dc12` to see what I changed in `setup.py` and `pwnlib/version.py`.

Afterwards the world looked like this:

* `stable` did not change.
* `beta` was at `ec98dc12 (tag: 3.10.0beta0) Release 3.10.0beta0`.
* `dev` was also at `ec98dc12`.

### Step 4

I created a new commit for the dev branch. Try doing `git show b62804ef` to see what I changed in `setup.py` and `pwnlib/version.py`.

* `stable` did not change
* `beta` did not change
* `dev` was at `b62804ef Begin working on 3.11.0`. Try doing `git show b62804ef`.

### Step 5

I created these github releases:

https://github.com/Gallopsled/pwntools/releases/tag/3.9.0
https://github.com/Gallopsled/pwntools/releases/tag/3.10.0beta0

**Comment by TethysSvensson** [comment]
@Arusekk @zachriggle: I hope this is a thorough enough description of how I did the release, that you can figure out how to do one yourself. If not, feel free to ask any follow-up questions.

You could also just throw it all out and do it differently if you prefer, since you are the current maintainers and can do whatever you want.

**Comment by Arusekk** [comment]
Done. Please make the actual release, since I am not a maintainer on PyPi

**Comment by TethysSvensson** [comment]
@Arusekk If you tell me which account to add, you will be.

**Comment by TethysSvensson** [comment]
Btw, you only pushed the commit with the 4.0.0beta0 tag to the beta-staging branch, not to the beta branch. :)

**Comment by Arusekk** [comment]
It's also [Arusekk](//pypi.org/user/Arusekk/)

**Comment by TethysSvensson** [comment]
@Arusekk Done. You are now an owner on pypi

**Comment by zachriggle** [comment]
What's the first version that will be released as Python3 compatible?

3.12 is the current "stable"
3.13 is the current "beta", and will be the new "stable"
3.14 is the current "dev", and will be the new "beta"
4.0beta0 is the current "dev3" and will be the new "beta3"?

Did I get that right?
