### ISSUE TITLE
Only works in interactive python shell

### ISSUE THREAD

**Issue by irodionzaytsev** [Gallopsled/pwntools#1396]
When in interactive python shell everything works as expected. In a script, however, after importing pwn, I get some strange behavior, for example printing a binary string prints its representation, e.g.
`print '\x90'  # prints ? character`
`import pwn`
`print '\x90' # prints \x90`

**Comment by Arusekk** [comment]
This is the expected behaviour. If you want to retain printing binary characters binary, please either set PWNLIB_NOTERM environment variable to 1, or use pwnlib instead of pwn.

Also please note that python 2, while still supported by pwntools, will not be supported by python itself soon, it is in less than a week (see http://pythonclock.org).

If you want to develop new software, feel encouraged to do so using python version 3.
