### ISSUE TITLE
Python3: cyclic not well-behaved with alternate alphabets

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1481]
It looks like we do not convert `alphabet` to be a `bytes` object:

```
>>> cyclic(32)
b'aaaabaaacaaadaaaeaaafaaagaaahaaa'
>>> cyclic(32, alphabet=string.ascii_lowercase)
'aaaabaaacaaadaaaeaaafaaagaaahaaa'
```

**Comment by Arusekk** [comment]
I did not plan this, but it turns out that cyclic returns object of the same type that alphabet. So you can use string.ascii_lowercase.encode() as a workaround for now.

**Comment by peace-maker** [comment]
This appears to be documented for the `cyclic` function to always return the type of the input alphabet. It's weird though, since the `context.cyclic_alphabet` attribute setter saves `alphabet.encode()` and thus forces a `bytes` object. But that's used internally in e.g. the rop module, so forcing bytes there is reasonable.

I think keeping the current behavior is fine since it's documented and people might already rely on it.

Do you consider changing cyclic behavior?
