### ISSUE TITLE
can't use gdb.attach,who can help me.

### ISSUE THREAD

**Issue by r4b3rt** [Gallopsled/pwntools#1514]
# Pwntools Issue Template

Thanks for contributing to Pwntools!

When reporting an issue, be sure that you are running the latest released version of pwntools (`pip install --upgrade pwntools`).

Please verify that your issue occurs on 64-bit Ubuntu 14.04.  You can use the Dockerfile on `docker.io` for quick testing.

```
$ docker pull pwntools/pwntools:stable
$ docker run -it pwntools/pwntools:stable
```

If possible, provide a proof-of-concept which demonstrates the problem.  Include any binaries or scripts necessary to reproduce the issue, and please include the full debug output via setting the environment variable `PWNLIB_DEBUG=1`.

cat test.py 
#!/usr/bin/env python3

from pwn import *

context.terminal = ['tmux', 'split', '-h']

bash = process('/bin/bash')
gdb.attach(bash, gdbscript = '''
p "hello from pwnlib"
c
''')
bash.interactive()
root@ubuntu:/home/r0hf/Pwns/pwn2# ./test.py 
$<5>[$<2>+] Starting local process '/bin/bash': pid 6212
$<5>[$<2>*] running in new terminal: /usr/bin/gdb -q  "/bin/bash" 6212 -x "/tmp/pwn_25e6h9m.gdb"
$<5>[$<2>-] Waiting for debugger: Failed
$<5>Traceback (most recent call last):
  File "./test.py", line 11, in <module>
    ''')
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/context/__init__.py", line 1441, in setter
    return function(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/gdb.py", line 791, in attach
    proc.wait_for_debugger(pid, gdb_pid)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/util/proc.py", line 349, in wait_for_debugger
    l.error("debugger exited! (maybe check /proc/sys/kernel/yama/ptrace_scope)")
AttributeError: 'Progress' object has no attribute 'error'

**Comment by Arusekk** [comment]
Sorry about this, this has already been fixed in dev branch, but as you can see in the trace, please check yama ptrace scope. It needs to be disabled in some rare corner cases.

**Comment by zachriggle** [comment]
@Arusekk can we back port the fix to `stable` and do a point release?

**Comment by Arusekk** [comment]
Well, we even should, but I am a little busy mending the roof in my house (maybe sounds like 'the dog ate my homework' but for real). I guess we need more devs? ops? devops? Actually we need me (or someone) to automatize common work done during releases (you can see some of my [desperate DevOps efforts](https://github.com/Arusekk/pwntools/actions) on my fork).
Ideally I would like to have a GUI button on GH that says 'hey cherry pick this commit(s) to stable, test it, and if it passes, tag a release, update changelog (oh yeah), and upload stuff to PyPI' but apparently they have not made one yet, so I keep trying.

As a side note, GH has a feature of drafting releases, that can be just clicked 'ready' when time comes, tagging current head commit on the desired branch and launching some hooks ('actions') with the tag (this is what Arusekk/pwntools:4.1.1-test1 [or whatever I called it] tried to be).

@zachriggle are you allowed to, say, maintain the change log / tell me what features look backport-wanting, in some kind of machine-digestible form? It would be a huge burden lifted off my shoulders.
If someone wanted to help me write all that scripts / [yaml](https://noyaml.com), I would just love that. I don't get anything from it. Just the pure fun.

**Comment by zachriggle** [comment]
I am prohibited from contributing any changes at all, unfortunately.  It's an ongoing discussion with my managers.

I tried getting a very simple single-line commit submitted through FOSS approval and was shot down, hard.  ☹️

**Comment by zachriggle** [comment]
I think @TethysSvensson had some automation scripts, can you weigh in Mathias?

The easiest way to handle it is to simply request that bug-fixes target the `stable` branch and then just do an easy merge `stable -> beta` and then `beta -> dev` (do we even still have a beta branch?)

Having bug-fix change target `stable` automates the process of making "which changes" be machine-digestible.  I've also tried my hand at marking some issues with the `Backport-Required` tag.  We also *used* to have specific release numbers on individual issues / pull requests, which is another way to make it machine-digestible.  "Backports" are only required when bug-fixes target e.g. `dev` instead of `stable`.

**Comment by Arusekk** [comment]
I have something basic here: https://github.com/Arusekk/rozmaite/blob/master/pwntools-mkrelease.sh

**Comment by zachriggle** [comment]
Dig the script!  I would recommend testing it against the "test" environment of PyPI (https://packaging.python.org/guides/using-testpypi/) and on your own fork of Pwntools so that it doesn't clobber anything on the main repo while you work on it.

An important thing that might catch your up is that *currently* you cannot commit directly to either `stable` or `beta` without the CI tests completing.

The way we worked around this in the past is to branch off an e.g. `stable-staging` repo and push that to the main Pwntools repository.  All branches get tested, so these would go through CI.  After CI passes, you can do a FF merge and push the e.g. `stable` branch.  You might be able to automate this last part of the process through GH Actions.

**Comment by TaQini** [comment]
@r4b3rt  version `4.2.0b0` has fixed it : 
```bash
pip install -U pwntools==4.2.0b0 
```
