### ISSUE TITLE
GDB claims no such file or directory

### ISSUE THREAD

**Issue by M0cK1nG-b1Rd** [Gallopsled/pwntools#1656]
Hi there

The problem appeared when I tried to write a py script for a certain question
the script looks like:
```py
from pwn import *
context.log_level="debug"
io=process("./pwn1")
gdb.attach(io)
pause()
payload="A"*0x10
io.sendlineafter("Input:",payload)
io.interactive()
```
and when i tried to run the script, the problem came out:

```c
Reading symbols from ./pwn1...(no debugging symbols found)...done.
Attaching to program: /home/a709046532/Documents/pwn1, process 3881
Reading symbols from /lib/x86_64-linux-gnu/libc.so.6...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libc-2.29.so...done.
done.
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
0x00007fb37e01ff81 in __GI___libc_read (fd=0, 
    buf=0x7fb37e0f7a83 <_IO_2_1_stdin_+131>, nbytes=1)
    at ../sysdeps/unix/sysv/linux/read.c:26
26	../sysdeps/unix/sysv/linux/read.c: No such file or directory.
(gdb) 
```

Noticing that  `../sysdeps/unix/sysv/linux/read.c: No such file or directory.`  may be a key point, I went to StackOverflow for help and download  glibc-2.23 and use the command dir or  substitude to help gdb find the location. But the same problem appeared again when i run the script again.

I have try several times in Ubuntu20.04 19.04 18.04 and they throws out the same problem
The weired thing is that it can work on Ubuntu16.04, but it also throw out some unpleasant things at the end of the debugging like 

```c
0x00007f0ac0e7a320 in __read_nocancel ()
    at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
```

So can anyone help me locate the problem? I spent a whole night trying to figure it out and it's almost driving me crazy :(

**Comment by Arusekk** [comment]
You need to install libc6 sources.
Debian/Ubuntu:
```sh
$ sudo apt-get source libc6
```
(make sure your `/etc/apt/sources.list` has correct entries)

**Comment by M0cK1nG-b1Rd** [comment]
Thanks！The problem is solved.

**Comment by Davidrjx** [comment]
install libc6 and libc6-dev not works as expected

**Comment by ReDreamin** [comment]
> install libc6 and libc6-dev not works as expected

How did u solve it?

**Comment by adameus03** [comment]
`$ sudo apt install glibc-source`
`$ tar -xvf /usr/src/glibc/glibc-2.36.tar.xz -C /usr/src/glibc`
`$ gdb`
`(gdb) set substitute-path .. /usr/src/glibc/glibc-2.36`
`(gdb) set substitute-path . /usr/src/glibc/glibc-2.36`
`(gdb) attach <pid>`
It seems gdb couldn't find glibc sources, so that's what worked for me when I got annoyed by those "no such file directory" prints when directly debugging with gdb.
I don't really know why gdb needs substitution for both `.` and `..`, but I could line-by-line step through all the glibc backend code without being interrupted by the "no such file directory" issue.
