### ISSUE TITLE
Drop Travis CI

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1740]
It looks like the free OSS tier is dead.

https://news.ycombinator.com/item?id=25338983

**Comment by Arusekk** [comment]
It is just moving domains from https://travis-ci.org to https://travis-ci.com (but the transition is slow) — I believe we have to delete the project from .org first, since .com displays all Gallopsled repositories but pwntools. I lost permission to our account on travis-ci.org lately (maybe this was an accident), so I cannot do it myself rn.

**Comment by zachriggle** [comment]
If you need anything from me to make the transition, please let me know.

If we have to drop / temporarily disable Travis (due to the OSS tier being dead) I'm okay with that.

**Comment by heapcrash** [comment]
@Arusekk do you have access to the org on travis-ci.com?  I can't find any way to add users on travis-ci.org.

If you want, I can just disable the Pwntools project, since Travis CI builds are currently busticated anyway.

**Comment by Arusekk** [comment]
I don't know. The good news is https://travis-ci.com/organizations/Gallopsled/migrate shows it, so it will go through with hopefully no pain if you click it (I can't, it shows "Migration is not available for this account" and "not admin" next to Gallopsled in "Sign up for the beta" menu).

If this does not work, I will probably need to get admin access to Gallopsled org on GH, which I don't want yet (with great power comes great responsibility).
