### ISSUE TITLE
Implement RISC V architecture

### ISSUE THREAD

**Issue by hellow554** [Gallopsled/pwntools#1777]
* What the feature does
It will allow, e.g. `pwn.asm` output risc v instructions
* Why the feature should exit
It's an architecture here to stay ;) Should I elaborate this further?
* What tests should be included
Oh boy. Yes.

---

I'd like to write this

```python
import pwn
pwn.asm('add a0, a1, a0', arch='riscv')
```

and get `\x33\x85\xa5\x00`. Would be awesome (:

**Comment by Arusekk** [comment]
The best way to help is to submit some pull request.
There are several places where architecture-dependent stuff is:
* `pwnlib/context/__init__.py` so that the arch is recognized in the first place,
* `pwnlib/asm.py` so that you can do that stuff,

... and the best would be to add it to the following files as well so that it can go full featured:
* `pwnlib/abi.py`
* `pwnlib/data/syscalls/generate.py`
* `pwnlib/shellcraft/templates/<arch>/`
* `pwnlib/shellcraft/registers.py`
* `docs/source/shellcraft/<arch>.py`

You can do a quick `git grep aarch64` for an example of a well supported architecture and `git grep s390` for an architecture that is minimally supported. Have fun!
