### ISSUE TITLE
unexpected character while "encode('utf-8')"

### ISSUE THREAD

**Issue by DoubleMice** [Gallopsled/pwntools#1853]
https://github.com/Gallopsled/pwntools/blob/ec9dfe108b85ac47983e9a98808fcdbb50cb0cdd/pwnlib/util/packing.py#L587

eg:
```
shellcode = "\x99\xf7\xe2"
print(flat("padding\x00", shellcode))
```
what i want: `b"padding\x00\x99\xf7\xe2"`
buuut i got: `b'padding\x00\xc2\x99\xc3\xb7\xc3\xa2'`

maybe it's better to use `arg.encode('latin-1') ` to get an expected bytes string

**Comment by Arusekk** [comment]
(NOOOOOOOO!!!!....)

I've been telling this many people, countless times, but let me tell you once again: use a byte string.
In Python 3 there is finally a separate type for TEXT and a separate one for BINARY DATA. They are NOT THE SAME. They are totally different worlds. Using \xAA in text is just a shorthand (which should be removed IMO, since all it creates is bottomless confusion) for \u00AA. Do not use it. Use b'\x7f\x83' if this is what you mean. Do not use '\x7f\x83' unless you mean TEXT '\u007f\u0083', which is two codepoints looking like some letters with punctuation around them. This is intended behavior, and will not be altered.

Email z Piątek, 19 marca 2021 od DoubleMice:
> https://github.com/Gallopsled/pwntools/blob/ec9dfe108b85ac47983e9a98808fcdbb50cb0cdd/pwnlib/util/packing.py#L587
> 
> eg:
> ```
> shellcode = "\x99\xf7\xe2"
> print(flat("padding\x00", shellcode))
> ```
> what i want: `b"padding\x00\x99\xf7\xe2"`
> buuut i got: `b'padding\x00\xc2\x99\xc3\xb7\xc3\xa2'`
> 
> maybe it's better to use `arg.encode('latin-1') ` to get an expected bytes string
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Gallopsled/pwntools/issues/185

-- 
Wysłane z mojego urządzenia Sailfish

**Comment by heapcrash** [comment]
@Arusekk we need a documentation page (or maybe something on pwntools-tutorials) that discusses this topic, so we can link people to it instead of one-off comments and frustration on everybody's side.

Can we register a top-level exception handler that catches bytes-to-strings exceptions and recommends a particular URL for documentation?

**Comment by heapcrash** [comment]
@DoubleMice what you want to is use a byte-string instead of a text-string.  In Python3 these are very different things, as @Arusekk mentioned.  The problem is that e.g. `"\x99"` maps to the byte 0x99 on Python2, but on Python3 it could map to very many different things depending on encoding (latin-1, utf-8, utf-16. roman.

The solution is to make sure that Python knows you are describing a sequence of bytes, and for that you need the `b` prefix like `b'xyz'`.

Here's your example slightly rewritten to make it easier to see:

```
>>> shellcode = b"\x99\xf7\xe2"
>>> print(hexdump(flat("padding\x00", shellcode)))
00000000  70 61 64 64  69 6e 67 00  99 f7 e2                  │padd│ing·│···│
0000000b
```

Notice the `b` prefix on the quoted data, indicating that it is a byte-string, not a text-string. 

As a side note, I recommend using the `fit/fflat` dictionary so that you don't manually have to write padding, and get a cyclic offset finder for free:

```
>>> print(hexdump(flat({8: shellcode})))
00000000  61 61 61 61  62 61 61 61  99 f7 e2                  │aaaa│baaa│···│
0000000b
```

**Comment by heapcrash** [comment]
Specifically to address `arg.encode('latin-1')`, I was in that camp for a long while.  It has some PROs:

* 👍 1:1 mapping between text and bytes
* 👍 Seems very python2-like, which is convenient
* 👍 Don't have to worry about weird encodings like `utf-8` with placeholder bytes

But it also has some CONs:

* 👎 latin-1 `"\xff" != b"\xff"`
     * `b'\xff'.decode('latin-1') == b'\xff'` ⇒ `False`
     * `b'\xff'.decode('latin-1') == '\xff'` ⇒ `True`
* 👎 All characters in latin-1 are printable, which makes it harder to discern binary data
    * This is minor, but important for various Pwntools internals

There are some workarounds:

* `context.encoding` can save you in some cases when you pass in a string.
    * We need a `tutorials` page for this @Arusekk 
* You can set `context.encoding` in a config file, see the docs [here](https://docs.pwntools.com/en/stable/config.html)
    * We need a `tutorials` page for this, too @Arusekk 

Ultimately, Pwntools mainly deals in `bytes` as this removes any ambiguity as to what the actual data sent or received over-the-wire is.

If you want a `str`, you'll end up with some weird characters.  Python2 was a simpler time, and Pwntools still supports Python2 (for the moment) so you're free to use Py2 to write your scripts and not need to worry about character encoding.

```py
>>> '\xc9'.encode('latin-1')
b'\xc9'
>>> b'\xc9'.decode('latin-1')
'É'
```

For this reason, it's important that you use `bytes`.  There are a few places this is handled for you automatically, via `context.encoding`, e.g. `tube.recvlineS`, but for the most part, you should EXPLICITLY be using `bytes` and `b''` wherever possible.

**Comment by heapcrash** [comment]
@Arusekk Also, what do you think about forcing `unpack`, `u32`, `flat`, and other related functions to REQUIRE their arguments are `bytes` but not `str`?  This might help us shake out more bugs and raise more usable error messages.

Kind of counter-intuitive given that we have `context.encoding` but I think it would help prevent bug reports (and general user frustration).

**Comment by heapcrash** [comment]
@Arusekk I have added a "Bytes vs Strings" section to the tutorials here:
https://github.com/Gallopsled/pwntools-tutorial/blob/master/bytes.md

**Comment by Arusekk** [comment]
I guess this is some kind of a solution.

Email z Piątek, 19 marca 2021 od Heap Crash:
> @Arusekk Also, what do you think about forcing `unpack`, `u32`, `flat`, and other related functions to REQUIRE their arguments are `bytes` but not `str`?  This might help us shake out more bugs and raise more usable error messages.
> 
> Kind of counter-intuitive given that we have `context.encoding` but I think it would help prevent bug reports (and general user frustration).
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Gallopsled/pwntools/issues/1853#issuecomment-80273903

-- 
Wysłane z mojego urządzenia Sailfish

**Comment by Arusekk** [comment]
Oh!! This is a great idea, I think that a simple atexception() with

   if 'str' in msg and 'byte' in msg:
       print('See https://whatever.example for why you seem to not have understood Python 3 binary data vs text distinction')

Email z Piątek, 19 marca 2021 od Heap Crash:
> @Arusekk we need a documentation page (or maybe something on pwntools-tutorials) that discusses this topic, so we can link people to it instead of one-off comments and frustration on everybody's side.
> 
> Can we register a top-level exception handler that catches bytes-to-strings exceptions and recommends a particular URL for documentation?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Gallopsled/pwntools/issues/1853#issuecomment-80272053

-- 
Wysłane z mojego urządzenia Sailfish

**Comment by DoubleMice** [comment]
@heapcrash @Arusekk  YES, adding 'b' prefix can solve this, and I know `"\xff" != b"\xff"`.
But have you think about a situation that if one guy want to run his exploit script on py2 and py3 env?
My solution is what I posted beginning.
Could you have a better method to solve it?

**Comment by Arusekk** [comment]
b'\xff' works on py2

**Comment by DoubleMice** [comment]
@Arusekk Oh yes!! I am so stupid. It's my fault.
