### ISSUE TITLE
rwx checksec in response to recent linux kernel update

### ISSUE THREAD

**Issue by caprinux** [Gallopsled/pwntools#1919]
https://github.com/torvalds/linux/commit/9fccc5c0c99f238aa1b0460fccbdb30a887e7036

![image](https://user-images.githubusercontent.com/76640319/122515722-6e2f2580-d040-11eb-9e44-189d1cf574d0.png)

With the recently implemented Linux Kernel update being released onto the most recent Linux distros i.e. Ubuntu 20.04.2 LTS and Kali 2021.1, it appears that the default linux behavior to x86_64 binaries has been to turn off all **rwx** segments by default. 

This means that even if binaries do not disable the rwx, the linux kernel will do it for them. This has been implemented in the 5.8.0-55-generic kernel version. However, **checksec** appears to still mention **RWX: Has RWX semgents** when doing **checksec**. 

Perhaps this could be patched and pwntools could instead throw a separate warning 

**RWX may be present but has been disabled by the kernel.** 

Any opinion?

**Comment by heapcrash** [comment]
The fix for this is ultimately in `ELF.nx` which is currently a boolean.  To know whether this patch is applied, we have to know the kernel version.  This works nicely for "local" exploits, but not well for knowing what the remote system is running on.

It'll take some re-architecting to fix this and add a `warn_once` somewhere.

Not sure if the warning should be emitted on `ELF.nx` access (which is ultimately used by e.g. `rwx_segments`) or just on `ELF.checksec`.

If we have an `ssh` session we can trivially check the server kernel version, but for something that requires a TCP connection to a server (e.g. `remote()`) there's no way to know.

Need to think about how to handle this optimally.

Ideas / Problems:
* Add an `ssh=` optarg to the ELF constructor
* Add an e.g. `context.uname` or `context.kernel_version` (we already have `context.kernel`)
    * Different vendors may have kernel versions which *should* have this patch, but may not have adopted it (or back ported it)
* Just ALWAYS warn about it (and suggest setting `context.kernel_version`)
* Warn about it in `ssh.checksec`
* How should `ELF.rwx_segments` behave?
