### ISSUE TITLE
what is the meaning of PWN

### ISSUE THREAD

**Issue by JumHorn** [Gallopsled/pwntools#1940]
what is the meaning of PWN?
is it an abbreviation?
I have googled a lot and found nothing about it.
still confused about it...

**Comment by gogo2464** [comment]
This is an abbreviation for own. It mean take something. At the origins it is about to take over a base in video games. pwnlib is a tool to exploit memory corruption vulns. Of course here it is about to take something remotely because memory corruption vulnerabilities allows an attack to do so. The ethymology often move. :)

Fell free to join https://discord.gg/96VA2zvjCB :)

**Comment by Arusekk** [comment]
See Wikipedia for etymology and context: https://en.wikipedia.org/wiki/Pwn
