### ISSUE TITLE
Difference between sending payload with pwntools and piping payload from file.

### ISSUE THREAD

**Issue by LittaKake** [Gallopsled/pwntools#1943]
## P.sendline(payload) vs `./binary < payload.txt`.

Hi!

This might seem to be a trivial question, but for me it doesn't seem like it is.

I just recently started utilizing `pwntools` and have tried using it to exploit a ret2libc vulnerability. I have been successful to do so! This is the program I exploited.
```c
#include <stdio.h>

void vuln() {
    char buffer[256];
    gets(buffer);
}

int main() {
    vuln();
    return 0;
}
```
After exploiting the binary using `pwntools` I wrote the payload to a file like so
```python3
with open('payload.txt', 'wb') as w:
    w.write(payload)
```
I then wanted to see if doing `./binary < myfile.txt` would also give me a shell, because that should work(right?). However the binary just completes whilst no shell is given. No error messages or anything like that. Weird I thought. I then tried `cat payload.txt | ./binary`. Nothing.

I therefore tested to see if the payload is at fault by reading the payload from `payload.txt` and then `sendline` it to the process. Sure enough `pwntools` made it work again and I got a shell.

What exactly does `pwntools` do to send the payload that for example `cat myfile.txt | ./binary` does not?

**Comment by Arusekk** [comment]
You should do `cat myfile.txt - | ./binary` if you wish to do that (notice that first arg of cat is the file, and the other is a dash/stdin, which should copy data from myfile.txt and then follow up with interactive data supplied).

Pwntools does two 'non-trivial' things: first, it opens a [pseudo-terminal](https://man7.org/linux/man-pages/man7/pty.7.html) for the process, which is pretty much irrelevant here, and the second is that I bet your script ends with `p.interactive()`, doesn't it. It is a heavy code for getting your input and supplying it to the process being run. Try to remove that and see that it completes the process, too.

Closing as this is expected behavior of pwntools, but feel free to write to someone on our Discord server (link in the [README](/Gallopsled/pwntools#readme)), or here if you don't trust that Discord thing.

**Comment by peace-maker** [comment]
Your payload might lack a newline character at the end, which is appended by `sendline` and expected by `gets`, but missing in the file you've written your payload to.
