### ISSUE TITLE
pwnlib.term.readline breaks return type of sys.stdin.readline

### ISSUE THREAD

**Issue by tkmikan** [Gallopsled/pwntools#1944]
By default, `sys.stdin.readline()` returns a `str`.
However, after `sys.stdin` is wrapped at `pwnlib.term.readline`, `sys.stdin.readline()` returns `bytes`, which may break other things, e.g. Telnetlib.
https://github.com/Gallopsled/pwntools/blob/bd12d1874f17e1fd6a9b26411ccc7ccd6c31f4cb/pwnlib/term/readline.py#L490

A simple testcase in the pwntools docker
```py
pwntools@d420d8f33e0f:~$ pwn version
[*] Pwntools v4.6.0
pwntools@d420d8f33e0f:~$ cat test.py
import sys
print(sys.stdin)
print(repr(sys.stdin.readline()))
from pwn import *
print(sys.stdin)
print(repr(sys.stdin.readline()))

pwntools@d420d8f33e0f:~$ python3 test.py
<_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>
aa
'aa\n'
<pwnlib.term.readline.init.<locals>.Wrapper object at 0x7fd94c58f160>
bb
b'bb\n'
```

**Comment by zachriggle** [comment]
@tkmikan Thanks for reporting this issue!  I'm not sure what the best way to handle this is, especially due to how Pwntools has an opinionated view of "Everything should be bytes" to avoid `str`-vs-`bytes` issues.

@Arusekk do you have ideas here?  You know the Py3 stack better than me for a long time now.
