### ISSUE TITLE
Pwntools v4.8.0  shellcraft AttributeError

### ISSUE THREAD

**Issue by ws0117** [Gallopsled/pwntools#1956]
pwn version
[*] Pwntools v4.8.0dev-dev-bd12d18

>>> from pwn import *
>>> shellcraft.open('a.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxxx/pwntools/pwnlib/shellcraft/__init__.py", line 90, in __getattr__
    raise AttributeError("'module' object has no attribute '%s'" % key)
AttributeError: 'module' object has no attribute 'open'

**Comment by Arusekk** [comment]
Details? Have you read the issue template? Please procide the details on how to reproduce it, so that we can see if your use is valid, and hopefully fix it

**Comment by heapcrash** [comment]
ws0117, please try reproducing this from to official Docker image.  I
wasn't able to reproduce this.

$ docker run -it pwntools/pwntools:stable
***@***.***:~$ python3 -q
>>> from pwn import *
>>> print(shellcraft.open('a.txt'))
    /* open(file='a.txt', oflag=0, mode=0) */
    /* push b'a.txt\x00' */
    push 0x74
    push 0x78742e61
    mov ebx, esp
    xor ecx, ecx
    xor edx, edx
    /* call open() */
    push SYS_open /* 5 */
    pop eax
    int 0x80

**Comment by peace-maker** [comment]
I had a similar problem when using a pwntools copy cloned on windows in wsl. The `syscalls` symlink back to the shellcraft/templates/common folder was broken due to cloning on windows, so the extracted syscalls couldn't be found for any architecture. Manually recreating those symlinks fixed it for my dev setup.
