### ISSUE TITLE
radare2 integration 

### ISSUE THREAD

**Issue by gogo2464** [Gallopsled/pwntools#1968]
* What the feature does

This feature open an radare2 terminal with the line radare2.attach(p). It should be able to give to radare2 the current state of the binary like with gdb.attach(p).

* Why the feature should exist

Many people use Radare2 instead of gdb. Radare2 is a real framework of reverse engineering and is really made to reverse binaries contrary to gdb that is just a debugger. In r2 you can for example view graph in the binary. I personally think r2 is better to reverse and exploit binaries than gdb.

* What tests should be included

Same tests as gdb.attach(p)

Duplicate of https://github.com/Gallopsled/pwntools/issues/965. I developped more the suggestion to avoid to be closed like the last issue.

**Comment by zachriggle** [comment]
This should be relatively easy to implement in an ad-hoc manner, due to the way `pwnlib.gdb.binary` is implemented:

https://github.com/Gallopsled/pwntools/blob/4c78e188ce608d6cb51088a96fbf692b821b99c6/pwnlib/gdb.py#L603-L628

If you like, you can create a wrapper script named `pwntools-gdb` that implements whatever backend you'd like.  The only requirement (back on Pwntools' side) is that it will halt the exploit script until a debugger is attached to the target process.

**Comment by gogo2464** [comment]
@zachriggle Why did you close this issue? I could implement both the gdb backend in pwntools as well as the radare2 usage in pwntools too. 

I plan to integrate this script in pwntools: https://github.com/ps1337/pwntools-r2
