### ISSUE TITLE
Increasing the size of a section (rodata) in ELF binary

### ISSUE THREAD

**Issue by Nikhil1212** [Gallopsled/pwntools#1971]
Hi everyone,
I would like to add a new string constant to my binary (ELF). So, for that, I want to increase the size of the rodata section so that my constant string fits in rodata. May I know how we can increase the size of a particular section (rodata) using pwntools.

Thanks for the help

**Comment by Arusekk** [comment]
Answered privately via mail, but pasting here for future scavengers:
> I guess that your best chance would be to use patchelf (not sure if it can do that), or to change the .rodata section length and the relevant PT_LOAD segment with r-- permissions. Note that it will most likely not work if your rodata is not at the end of the file and the size is not helpful, because you will quite probably need to insert an extra memory page (pages are 4096 bytes long on most architectures).


> The memory layout is typically like this (and in this order):
[.text] [.rodata] [.got] [.data] [.bss] [maybe empty space, maybe randomized] [heap]


> The bad news is that the binary can have hardcoded pc-relative offsets to .data (and to .got!) in its .text, so you might fail in that case, unless you also modify the offsets to .got and to all the variables in .data.
To be really sure that nothing goes wrong you should re-link the object files, adding an extra object file of your interest, because linking is a destructive process (if you don't have it, you can try some ad-hoc disassembly, but I am not sure how well that can go).


> You can also insert an extra PT_LOAD segment with read-only permissions; your data will not go to the .rodata section, but it will be read-only (at a different offset, I would try to insert it at a negative offset before the first PT_LOADed page, or right after the .bss).
