### ISSUE TITLE
Error creating ROP object

### ISSUE THREAD

**Issue by Nj0be** [Gallopsled/pwntools#2047]
I get an error when I create a ROP object after modifying the address of the ELF object. It doesn't happen if I don't change it. The address is valid (0x7f9a3d0e3000)

Code:
...
libc = ELF('./libc.so.6')
...
libc.address = libc_base
...
libc_rop = ROP(libc)      # error!

Traceback (most recent call last):
  File "/mnt/Data/dev/CTF/OliCyber/software/terminator/exploit.py", line 64, in <module>
    libc_rop = ROP(libc)
  File "/home/benia/.local/lib/python3.10/site-packages/pwnlib/rop/rop.py", line 598, in __init__
    self.__load()
  File "/home/benia/.local/lib/python3.10/site-packages/pwnlib/rop/rop.py", line 1322, in __load
    if set(pack(addr)) & self._badchars:
  File "/home/benia/.local/lib/python3.10/site-packages/pwnlib/util/packing.py", line 149, in pack
    raise ValueError("pack(): number does not fit within word_size [%i, %r, %r]" % (0, number, limit))
ValueError: pack(): number does not fit within word_size [0, 140300427372864, 4294967296]

**Comment by Arusekk** [comment]
The error could have been nicer, it could also guess the correct context variables by itself, but you generally need to set [`context`][ctx][`.bits`](https://docs.pwntools.com/en/stable/context.html#pwnlib.context.ContextType.bits), or, better yet, [`context`][ctx][`.arch`](https://docs.pwntools.com/en/stable/context.html#pwnlib.context.ContextType.arch) in order not to shoot yourself in the foot anyway. Try to use the [`pwn template`](https://docs.pwntools.com/en/stable/commandline.html#pwn-template) for best experience, because it uses [`context`][ctx][`.binary`](https://docs.pwntools.com/en/stable/context.html#pwnlib.context.ContextType.binary), which sets all the possible context variables automatically.

[ctx]: https://docs.pwntools.com/en/stable/context.html

**Comment by Nj0be** [comment]
I didn't know that I could set those context variables, now the error has gone. Thanks for your quick response!
