### ISSUE TITLE
Building Docs Breaks on Python 3.10

### ISSUE THREAD

**Issue by bocajspear1** [Gallopsled/pwntools#2057]
Attempting to build the docs with Python 3.10, which is now the default in Kali Linux causes an error:
```
$ git clone https://github.com/Gallopsled/pwntools.git
$ cd pwntools/
$ cd docs
$ python3 -m venv ./venv
$ source ./venv/bin/activate
$ python3 -m pip install -q pwntools
$ python3 -m pip install -r requirements.txt 
...
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v4.5.0

Extension error:
Could not import extension sphinxcontrib.napoleon (exception: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py))
make: *** [Makefile:53: html] Error 2
```

Other info:
```
$ pip list | grep pwntools
pwntools                      4.8.0
```
```
$ python3 --version
Python 3.10.4
```
```
$ cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.2"
VERSION_ID="2022.2"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
```

Found this in the Sphinx repo: https://github.com/sphinx-doc/sphinx/issues/10378/. If I change in `source/conf.py`: 
```
'sphinxcontrib.napoleon'
```
to
```
'sphinx.ext.napoleon'
```
it works.

**Comment by u91o** [comment]
It's a backwards-compat thing. In 3.10 you'll have to do `from collection.abc import Callable`. I ran into the same problem while trying to fix the dash directive in the docs Makefile, but since officially pwntools only supports Ubuntu LTS releases (14.04, 16.04, 18.04, and 20.04) and they are only on 3.9, I think it's a non-issue for now.
