### ISSUE TITLE
Add libc to pwn template

### ISSUE THREAD

**Issue by ghsi10** [Gallopsled/pwntools#2076]
I think it would be nice to add a libc flag to the pwn template.

exmaple:
pwn template --host HOST --port PORT **--libc=LIBC**  ./EXE

**Comment by peace-maker** [comment]
I've started to implement something similar the pwninit tools which allows you to run the binary using different libraries a while ago.

https://github.com/Gallopsled/pwntools/compare/dev...peace-maker:pwntools:download_libc_libraries

The workflow would be to add `pwn template --host p.wn --port 1337 --libc ./libc.so.6 ./challenge` which generates new code into the template. By default it'd use the given libc file to launch the binary, but you could run your exploit with `LOCAL_LIBC` to use the system libc instead. It'd download and cache the matching ld.so and other libraries from the source packages after a lookup on libc.rip and use `patchelf` to set the RPATH and interpreter on the binary when run with the remote libc. It'd create a temporary copy of the challenge binary to change RPATH, to keep the original one untouched.

The generated code in the template would look something like
```python
# Use the specified remote libc version unless explicitly told to use the
# local system version with the `LOCAL_LIBC` argument.
# ./exploit.py LOCAL LOCAL_LIBC
if args.LOCAL_LIBC:
    libc = exe.libc
elif args.LOCAL:
    library_path = libcdb.download_libraries('./libc.so.6')
    if library_path:
        exe = context.binary = ELF.patch_custom_libraries('./challenge', library_path)
        libc = exe.libc
    else:
        libc = ELF('./libc.so.6')
else:
    libc = ELF('./libc.so.6')
```

I asked around and people preferred to use the specified remote libc by default and only opt-in to use the system libc instead of the other way around with a `REMOTE_LIBC` option.

One could probably implement more sources to look for the matching ld.so and libraries like launchpad, since the package might be removed from the original mirror where libc-database got the libc from pointed to in [libs_url](https://github.com/niklasb/libc-database/blob/8ecf25955b567b6b2c3dcb022306787fbe1eed9d/searchengine/api.yml#L85).

Is this something to be integrated into pwntools or should it stay in separate tools since it's so flaky to find the correct ld.so? `ELF.patch_custom_libraries('./challenge', library_path)` is still useful to optionally start the binary with different libraries - whereever they came from?

Python 2 support was a pain btw D:

**Comment by Arusekk** [comment]
Wow! @peace-maker that is a huge nice thing.
I have always used some `unshare -cR. ./challenge` plumbing instead of `patchelf` (it requires unprivileged user namespaces, but avoids any modifications to the binaries, providing a small tiny bit of isolation at the same time).  I wonder if the py2 support is really worth it here; as far as I can see, the libs can be downloaded once when generating the template, which only goes with `pwn template --libc ...` so we might *technically* force py3-only behaviour here.  Like with the `inspect.signature` bit I decided earlier in one of the PRs for py3.11 support.

**Comment by Arusekk** [comment]
Also, I like streaming and on-line parsing of archives as long as it is possible (that unix-ar lib looks like it fails to be able to do so currently, so no worries I guess), instead of processing the whole thing in memory (I know, the libc's libs are small enough to fit in any RAM anyway, but that's just a nice way to cut the connection before receiving all of the data in some cases probably, and save some time if one has slow uplink; we do not usually need libmvec.so and libthread_db.so, right?).

**Comment by peace-maker** [comment]
I liked the idea of the exploit script being self contained and redownloading the libs when run in a different environment. So downloading them once when generating the template feels like a downgrade. Now that the python 2 support is already implemented, it's not that important to drop the support from my side.

We could think about only saving the buildid in the script, so you don't even have to have the libc binary.

The other direction I'd like the template to handle somehow is when you're given the libc and matching ld. Like a --lib-path argument which patches the RUNPATH of the binary to that path without trying to lookup anything.

Do you think unshare is a worthwhile alternative solution if patchelf isn't available? I've never used it.
