### ISSUE TITLE
ROP support for passing registers as arguments

### ISSUE THREAD

**Issue by jonomango** [Gallopsled/pwntools#2206]
The ROP module is very useful, but I haven't found a way to easily read from registers or pass specific registers as arguments to `ROP.call()`.

For example, let's say we have a function called `func1()` that returns a value (in RAX). It is currently very difficult to find a way to pass the return value along to another function. Ideally, we would write something like this and everything would just "work":

```python
rop.call(func1)
rop.call(func2, regs.rax)
```

I don't think it would be *too hard* to implement this. In the above example, it would just be finding a gadget that moves `rax` into `rdi` between the calls. Is there something that I'm missing?

**Comment by Arusekk** [comment]
Currently this is straight up impossible, since the implementation only searches for `pop REG; ret` gadgets. If you wish to work on that, feel free to reopen the issue, but I doubt if you can finish without putting in much effort and probably even refactoring the rop module a bit.

For now, you should either manually add the gadget in between (`rop.func1(); rop.raw(YOUR_GADGET); rop.func2()`), or assume the returned value (file descriptors are allocated deterministically, for example).

Also, such stray `mov rdi, rax` gadgets are quite rare. If your desired function `func2()` is designed to always be called with the result of some other function call, you may want to find `mov rdi, rax; call func2; ...` somewhere where the code actually calls your `func2` of choice using the pattern and does not do anything special afterwards if desired. You can then use func2 call site as a special 'function' with a different ABI — taking its first argument in rax instead of rdi.
