### ISSUE TITLE
the result of target remote match is wrong when we attach gdb with "gdb.attach(('0.0.0.0',1234))"

### ISSUE THREAD

**Issue by ckxckx** [Gallopsled/pwntools#2290]
when use gdb.attach(('0.0.0.0',1234)),
failed to find the correct pid for local process
```       
 if not (raddrs & remote):  # maybe here is a bug, edit it to " laddrs & remote"
    return False
if local is None:
    return True
return bool(laddrs & local)

```

![image](https://github.com/Gallopsled/pwntools/assets/18208119/1d33a9b3-e86c-4c82-9a9f-9d69fda0903b)
![image](https://github.com/Gallopsled/pwntools/assets/18208119/a331e1b2-d957-422a-9dab-87db878e3b2e)

**Comment by Arusekk** [comment]
Email z wtorku 31 października 2023 od ckxckxa:
> when use gdb.attach(('0.0.0.0',1234)),
> failed to find the correct pid for local process
> ```       
>  if not (raddrs & remote):  # maybe here is a bug, edit it to " laddrs & remote"
>     return False
> if local is None:
>     return True
> return bool(laddrs & local)
> 
> ```
> 
> ![image](https://github.com/Gallopsled/pwntools/assets/18208119/1d33a9b3-e86c-4c82-9a9f-9d69fda0903b)
> ![image](https://github.com/Gallopsled/pwntools/assets/18208119/a331e1b2-d957-422a-9dab-87db878e3b2e)
> 
> 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/Gallopsled/pwntools/issues/2290
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***

Could you elaborate? Currently your description is not exactly complete. How do you start your server? What is the output of netstat -plnt or ss -plnt? What version of pwntools do you use (pwn version)? Does it work with the suggested change? If so, would you mind submitting a pull request or pasting a patch here?

Please remember to stick to a template when reporting bugs to open source projects whenever possible. The minimum should always be: what have you done and how (think about the maintainers having to understand it and so the same steps), what did you expext to happen, and what happened instead. Please try to be clear and precise, and use text instead of images unless they carry some extra meaning (like when reporting GPU bugs).

-- 
Wysłane z mojego urządzenia Sailfish

**Comment by ckxckx** [comment]
Here is the testcase:
[testcase.zip](https://github.com/Gallopsled/pwntools/files/13214247/testcase.zip)

Test with `make testpwn`:

before the patch, testpwntool.py will fail like below:
<img width="923" alt="image" src="https://github.com/Gallopsled/pwntools/assets/18208119/11f66f63-8d93-465c-84a9-9e87187b71b1">


## Setting
python version :
```
(v310) @root➜  pwntools git:(dev) python3 --version
Python 3.10.12
```
pwntools version: build from the latest code which is clone from `https://github.com/Gallopsled/pwntools`

**Comment by ckxckx** [comment]
Here is the testcase:
[testcase.zip](https://github.com/Gallopsled/pwntools/files/13214360/testcase.zip)


Test with `make testpwn`:

before the patch, testpwntool.py will fail like below:
<img width="923" alt="image" src="https://github.com/Gallopsled/pwntools/assets/18208119/11f66f63-8d93-465c-84a9-9e87187b71b1">


## Setting
python version :
```
(v310) @root➜  pwntools git:(dev) python3 --version
Python 3.10.12
```
pwntools version: build from the latest code which is clone from `https://github.com/Gallopsled/pwntools`
