### ISSUE TITLE
Questions about Copilot + Open Source Software Hierarchy

### ISSUE THREAD

**Issue by liaochris** [Gallopsled/pwntools#2375]
Hi! My name is Chris and I'm writing a thesis on Open Source Software. I'm trying to collect/validate my data and I have two questions for the maintainers of this project.
1) Did this project receive free github copilot access on June 2022?
2) My thesis is especially focused on understanding hierarchical structures. Would it be possible to share a list of individuals in this project with triage/write/maintain/admin access in this project? I understand this may be confidential information, so please feel free to share it with [chrisliao@uchicago.edu ](chrisliao@uchicago.edu)

**Comment by peace-maker** [comment]
Hi Chris, I wasn't maintainer of this project yet in June 2022 but haven't seen any talk about Copilot access. Maybe @Arusekk knows.
Regarding admin access to this project there are 6(+1) people listed most of which contributed heavily during earlier phases of pwntools and moved on to other things now. The +1 is Zach Riggle who unfortunately passed away last year. We don't have any hierarchy in place. I don't want to mention other people not on the [public list](https://github.com/orgs/Gallopsled/people) since they might have chosen to hide their membership on purpose. What do you use those lists for?
Please do post back after you're done and good luck with your thesis!
