### ISSUE TITLE
[bug] kitty debugging window doesn't close when exiting process

### ISSUE THREAD

**Issue by k4lizen** [Gallopsled/pwntools#2428]
This issue is in regards to debugging a process and `context.terminal`. When using tmux, one can do this:
```python
context.terminal = "tmux splitw -h -l 65% -b".split()
```
to have the debug window be a split, be on the left, and have it be 65% of the total window size. In this case, closing the process window (i.e. pane in tmux terminology) (the nondebugging one), the debugger also gets closed automatically. This is really convenient as running debugging can happen quite often and manually closing the debugging window can take a few too many keystrokes. This also works properly in kitty when:
```python
context.terminal = "kitty"
```
~~However, kitty doesn't natively support setting the window size with command line arguments (https://github.com/kovidgoyal/kitty/issues/7634) (and having to do that manually is pain), so the workaround is...~~
`--bias` was added to kitty. Now the kitty equivalent of the tmux command is just:
```python
context.terminal = "kitty @ launch --location=before --cwd=current --bias=65".split()
```

And from what I can observe, everything works properly *except* that exiting the process (for example ctrl+c) doesn't kill the debugging window.

**Comment by k4lizen** [comment]
That being said, with the previous solution (with the bash script, before `--bias` was added) when one exited gdb (via `exit` or Ctrl+D) it would continue off as a normal shell, but now exiting gdb kills the debugging window (and the process is stopped as well, which is the same as before). So its now possible to exit a "debugging session" with just Ctrl+D on gdb (whereas Ctrl+C on the process window (pane) works on tmux).

So I am now fairly content with the state of things (though figuring out the issue and making it more consistant across terminals would be nice).

**Comment by peace-maker** [comment]
The problem is usually that we don't get the pid of the process launched in the new terminal window but that of the forking parent terminal process.

For tmux there is special handling to get the pid of the child. You could try adding something similar for kitty in `misc.run_in_new_terminal`.

https://github.com/Gallopsled/pwntools/blob/cdfd64f6de1252170657defc5899207d54483022/pwnlib/util/misc.py#L389-L393

https://github.com/Gallopsled/pwntools/blob/cdfd64f6de1252170657defc5899207d54483022/pwnlib/util/misc.py#L451-L458
