### ISSUE TITLE
Arm support in the rop module

### ISSUE THREAD

**Issue by kokjo** [Gallopsled/pwntools#330]

**Comment by IdolfHatler** [comment]
I am going to put this as milestone "Someday", unless you want to do it yourself, in which case I think we can do it before 2.3.

**Comment by zachriggle** [comment]
I had put a lot of work into this, as well as supporting Windows x86 and x64 ROP generation.  That work has successfully been lost.

There are a few features that need to come along with this, and should help at least inform the implementer along the way:

## Minimum Set of Gadgets

http://en.wikipedia.org/wiki/Set_cover_problem

Given a lot of gadgets, there is a minimum number of gadgets needed to control any number of registers.  We need to implement support for this, for all architectures.  "pop eax / pop ebx / ret" is better than two individual "pop" gadgets.

## Different Calling Conventions

In order to support arbitrary architectures and calling conventions, we need a way to codify them.  What I'd had before was a way to specify the order of arguments, including support for specifying register vs. stack-offset arguments.  Both are necessary for Windows x64 (which uses rcx/rdx/r8/r9 then stack).

Additionally, there needs to be a way to specify stack alignment.  Some 64-bit issues arise when the stack is not aligned to a 32-byte boundary when entering a library routine (generally Windows x64).

Finally, there needs to be a way to specify stack argument padding.  Even though it's unused, the caller is responsible for allocating stack space for the first four arguments on Windows x64,  This is used for small routines to avoid them needing to allocate more stack space (it's generally allocated in the caller's prologue).

Essentially, you need to be able to capture all of this information:
- For each argument, is it in a register or on the stack.
- What is the offset of the first stack argument, from the top of the stack
- How many bytes of stack space *must* be reserved (important for jumping over it, since the routines will actually modify this data)
- Stack alignment.  This necessarily must assume the stack is already aligned properly as a result of the exploit, or expressly by the user padding with RET gadgets, but if we have multiple calls, we need to make sure the Nth one remains aligned.

## Register Scraping

Rudimentary support for scraping register offsets is needed.  For example, we should be able to determine that the sequence of "pop eax; pop ebx; sub rsp, 0x20;" will not only move the stack pointer by 0x28 bytes (assuming x86) but also puts eax at esp+0, and ebx at esp+4.

We can generally just throw out everything that doesn't conform to this pattern.  If there aren't infinite gadgets to make our life easy, it's generally something that has to be hand-coded anyway.

This is pretty much required for Windows x86 and ARM support.  ARM gets a bit more tricky, since we can pop multiple registers in a single instruction, but it's just a parsing issue.

**Comment by kokjo** [comment]
see PR #369

**Comment by zachriggle** [comment]
Closing this since the PR is closed
