### ISSUE TITLE
cyclic defaults

### ISSUE THREAD

**Issue by RobertLarsen** [Gallopsled/pwntools#484]
Should the 'n' argument in 'cyclic' and 'cyclic_find' not default to the 'word_size' of the current architecture?

**Comment by zachriggle** [comment]
I agree with this.  I had a long chat with another user who was bit by this recently.

Zach Riggle

**Comment by zachriggle** [comment]
Actually, I think after a very long discussion with the other user, I think we decided the best way to ensure backward compatibility is to default to 4 bytes.

The current functionality defaults to 4 bytes for `cyclic()` and `cyclic_find()` defaults to the size of the input.  For currently-working exploits, this means that `cyclic_find()` will operate on a 4-byte pattern.

Changing this behavior would break existing amd64 exploits that did not specify `n`.

However, setting the default to be 4, rather than inferred from the size of the input string, should break *less* things.

This way, users who want a large pattern must *manually* specify a size of 8, as they would already need to be doing for `cyclic`, but are not required to do so for `cyclic_find`.

What do you think about this approach (default=4 instead of default=word_size)?

**Comment by RobertLarsen** [comment]
Hmm...would you ever use n=4 with amd64 exploits?
We have broken backwards compatibility before when it made sense. I have never used the cyclic_find() function and cannot see how I should since I never have seen data go back from the exploited process...only through gdb so I always look up using the 'cyclic' cmd. line tool.
Maybe I'm just being pedantic but fx the 'flat' function converts integers to word_size byte arrays so I would expect cyclic to do the same.

**Comment by zachriggle** [comment]
`n=4` is currently the default for `amd64` exploits for patterns generated by `cyclic`, as well as by the `cyclic` command-line tool.

The only requirement on cyclic is that it creates a pattern with no repeating sub-sequences of size `n`.  In order to find the offset of a sub-sequence, `cyclic_find` currently infers the subsequence size from the length of the input.  This leads to problems when somebody does this:

```
context.arch='amd64'
...
buffer = cyclic(512)
...
# RIP=caaadaaa at crash
offset = cyclic_find('caaadaaa')
```

This will not work correctly, because the `n` from `cyclic` differs from the `n` of `cyclic_find`.  As currently implemented, the user would need to instead explicitly specify, or manually truncate:

```
offset = cyclic_find('caaa')
offset = cyclic_find('caaadaaa', n=4)
```

The way that I would prefer it works is that `cyclic` remains entirely unchanged, and `cyclic_find` should truncate the input to the same default length as `cyclic`.  `cyclic` must remain unchanged for backward compatibility (i.e. not ruining offsets of every 64-bit exploit ever written that uses cyclic_find() to find offsets at runtime).  Truncating the length of `cyclic_find` to 4 by default should not have any negative consequences for existing `amd64` exploits, as I've not ever actually seen anybody explicitly specify e.g. `cyclic(512, n=8)`.

**Comment by zachriggle** [comment]
The above comment is how this works in Binjitsu / Pwntools master.

```
>>> with context.local(arch='i386'): print(cyclic(32), cyclic_find('gaaa'))
('aaaabaaacaaadaaaeaaafaaagaaahaaa', 24)
>>> with context.local(arch='amd64'): print(cyclic(32), cyclic_find('gaaa'))
('aaaabaaacaaadaaaeaaafaaagaaahaaa', 24)
>>> with context.local(arch='amd64'): print(cyclic(32), cyclic_find('gaaahaaa'))
[!] cyclic_find() expects 4-byte subsequences by default, you gave 'gaaahaaa'
    Unless you specified cyclic(..., n=8), you probably just want the first 4 bytes.
    Truncating the data at 4 bytes.  Specify cyclic_find(..., n=8) to override this.
('aaaabaaacaaadaaaeaaafaaagaaahaaa', 24)
```
