### ISSUE TITLE
Pwntools does not work on 32-bit Ubuntu

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#518]
There are several reasons it doesn't work on Ubuntu i686.  Among them, only two really matter:
- Prolific use of `int()` instead of `long()` which causes issues with numbers larger than 2**32-1
- Unit tests assume 64-bit ELF binaries on the system.  This also impedes OSX support.
- Unit tests make assumptions about the random number generator.  e.g. in the `useragents` module.

Since I don't ever intend to run Ubuntu i686, and Travis does not have an option, I suggest we loudly warn users who are using a 32-bit Python.

Does this sound OK?  Something like:

``` py
if platform.processor() in ('i386', 'i486', 'i586', 'i686'):
    log.warn_once("Pwntools does not support 32-bit Python.  Use a 64-bit distro.")
```

**Comment by Idolf** [comment]
Sounds good to me.

**Comment by zachriggle** [comment]
Looks like some exception is throwing before we hit this warning

**Comment by zachriggle** [comment]
It looks like the issue is the trailing padding / alignment of the structures.

```
# 64-bit
>>> for name, field in pwnlib.elf.datatypes.elf_prstatus_amd64._fields_:
..:   print getattr(pwnlib.elf.datatypes.elf_prstatus_amd64, name).offset, getattr(pwnlib.elf.datatypes.elf_prstatus_amd64, name).size, name
0 12 pr_info
12 2 pr_cursig
16 8 pr_sigpend
24 8 pr_sighold
32 4 pr_pid
36 4 pr_ppid
40 4 pr_pgrp
44 4 pr_sid
48 16 pr_utime
64 16 pr_stime
80 16 pr_cutime
96 16 pr_cstime
112 216 pr_reg
328 4 pr_fpvalid
>>> ctypes.sizeof(pwnlib.elf.datatypes.elf_prstatus_amd64)
336

# 32-bit
(Pdb) for name, field in elf_prstatus_amd64._fields_: print getattr(elf_prstatus_amd64, name).offset, getattr(elf_prstatus_amd64, name).size, name
0 12 pr_info
12 2 pr_cursig
16 8 pr_sigpend
24 8 pr_sighold
32 4 pr_pid
36 4 pr_ppid
40 4 pr_pgrp
44 4 pr_sid
48 16 pr_utime
64 16 pr_stime
80 16 pr_cutime
96 16 pr_cstime
112 216 pr_reg
328 4 pr_fpvalid
(Pdb) ctypes.sizeof(elf_prstatus_amd64)
332
```

**Comment by AzureRabbit** [comment]
I have installed python3-pwntools using command "pip3 install git+https://github.com/arthaud/python3-pwntools.git", but problem still exsists.

OUTPUT:
ipython                                                                                                                                                                                        19:48:25   
Python 3.7.4 (default, Aug 21 2019, 14:02:05)                                                                                                                                                                 
Type 'copyright', 'credits' or 'license' for more information                                                                                                                                                 
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.                                                                                                                                           
                                                                                                                                                                                                              
In [1]: from pwn import *                                                                                                                                                                                     
---------------------------------------------------------------------------                                                                                                                                   
AssertionError                            Traceback (most recent call last)                                                                                                                                   
<ipython-input-1-308ef5371a41> in <module>                                                                                                                                                                    
----> 1 from pwn import *                                                                                                                                                                                     
                                                                                                                                                                                                              
~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pwn/__init__.py in <module>                                                                                                                               
      1 # Promote useful stuff to toplevel                                                                                                                                                                    
----> 2 from .toplevel import *                                                                                                                                                                               
      3                                                                                                                                                                                                       
      4 pwnlib.args.initialize()
      5 pwnlib.log.install_default_handler()

**Comment by Arusekk** [comment]
As your command implies, you installed from a different fork, which is no longer under development
https://github.com/arthaud/python3-pwntools/blob/de2854460b30beb4909e5f87007258862338a456/README.md#L10
https://github.com/arthaud/python3-pwntools/blob/de2854460b30beb4909e5f87007258862338a456/README.md#L10

**Comment by userse31** [comment]
So the sole reason its not on i686 is "don't feel like it"?

Excellent! Remind me to never invite you to any code porting projects.

**Comment by Arusekk** [comment]
I think the issue got resolved by now, thanks to Python 3 making more sense with numbers.

Is your issue still a thing? I have been using pwntools on a 32-bit ARM system with success, and I don't remember anything going exceptionally wrong.

**Comment by heapcrash** [comment]
The issue with supporting i686 as a *target* doesn’t exist.

Python2 has some nasty edges around the maximum value of an integer, that
make it difficult to support 64-but values AND have passing tests.  Tests
at all on i686 is impossible since no CI system supports that natively IIRC.

Is the failure you’re seeing a hard crash, or annoying warning?

**Comment by userse31** [comment]
I gave up trying to get some stupid python 2.7 script from 2017 working. I just don't have the patience for that.

Now as a coder, I like to develop my stuff on old OLD machines so that I make sure my stuff will work on almost anything.

So when I see people go all "lol, no 32 bit, we can't be bothered" it irritates me.

**Comment by Arusekk** [comment]
PRs are welcome of course, but this would be a bit of an undertaking, as Python 2 makes a distinction between ints vs longs—this mainly leads to problems when a 32-bit attacker is working on 64-bit binaries, but might appear all of a sudden in strange places.  It would be best to port your script to Python 3 if possible, because Python 2 will only get less support over time.

Also please do not mistake 'we are unable to solve this hard thing in the time we have, so let's warn that stuff may break' for 'I don't feel like it lol', many can find it disrespectful.
I get your point, but Python 2 is EOL and the fact that we still support it is already much from our side.  If your problem is still valid, please open a separate issue showing all the errors you are getting and the research you have done, or better yet, send a PR, because I do not have any 32-bit system now and cannot do this myself.
