### ISSUE TITLE
Filename confliction with checksec package on ArchLinux

### ISSUE THREAD

**Issue by jerry73204** [Gallopsled/pwntools#573]
I found the path "/usr/bin/checksec" is identical to a file from a pacman package "checksec" (on ArchLinux). I did have to rename this file manually. Could the file be renamed in further releases?

**Comment by br0ns** [comment]
@zachriggle What do you think?

**Comment by zachriggle** [comment]
We can probably just rename to pwncheck or something.

**Comment by zachriggle** [comment]
This seems like an issue that Arch needs to solve, not an issue which Pwntools / Binjitsu needs to solve.  Conflicting command names is a common issue (see `node` vs `nodejs` on Ubuntu).

**Comment by anthraxx** [comment]
its not an Arch problem, its the problem to "hijack" (no offense thats just the word that describes it best) binary names already used to other packages. the problem comes in place if you think about pwntools getting packaged for a dsitribution, that means the upstream provided names can't be used as they conflict with existing names and if they are not renamed they can't co-exists, however sometimes other dependencies expect a special implementation.
What if i call my next cool project python, should Arch solve that as it conflicts with the interpreter?

**Comment by zachriggle** [comment]
Yes, that is exactly what I mean.  That's an issue for the distro to resolve.  It's specifically why the `update-alternatives` command exists on Debian-based distributions.

Command names are not reserved for perpetuity on the basis of "I made a command with this name first".  ¯\_(ツ)_/¯

**Comment by anthraxx** [comment]
All the following is explicitly No offense but well sry that's a highly egoistic point of view. I just don't get it why it's such a problem to try to aim for a unique name so nothing conflicts. This update alternatives crap is a workaround to deal with the ubavoidable.  But well if that's how you like to care and handle such situations then it's your decision and I accept that

**Comment by zachriggle** [comment]
This request boils down to:

> Please rename your tool that you created as a replacement for an old, unmaintained, and broken tool, because we decided to change the name of the original from `checksec.sh` to `checksec` and your new, better, maintained tool's name conflicts with the one we chose to give it.  Only on Arch Linux does it conflict, but we'd like you to rename it upstream.

`checksec.sh` is an awesome tool, written by a cool dude (thanks tk!), but is [unmaintained](http://www.trapkit.de/tools/checksec.html) and broken (e.g. NX detection is wrong, and it doesn't work with some versions of Bash -- I mailed a patch two years ago, but it was never updated).

**Comment by anthraxx** [comment]
Well I don't want to argue about that further but I will explain what i mean in a more verbose way because i think you did not fully get my point. If you still disagree no need to make any followup as this will be by last point of view about this topic.

No that's not what it boils down to imho. Also not the decline is something that i consider partially egotistical, but the argumentation. In general (there will always be somewhere some exceptions or mistakes) but stuff in /usr/bin should not have implementation related file suffixes therefor .sh got stripped, the name is still checksec... best understanding for this is that upstream repo of numerous python things have default ```something.py``` but it will get rolled out as ```something```, thats just sane packaging... same applies for ruby.
However just because something is unmaintained, doesn't mean it does not exist or has no justification and needs to be "taken over". While I agree that solving conflicts (I name them fuckups) is something that is the responsibility of a maintainer, its still just a unavoidable fixing/workaround of a fuckup situation :smile_cat: My point of view is just that forceful name conflicts are avoidable so they can (for whatever reason) coexist with any other. pwnchecksec doesn't sound bad either. From a UX point of view its more clearer to any user what a particular command is about. The situation for checksec may not be so problematic to understand what I mean specifically, but take a look at the numerous sslscan forks and re-implementations under the same name and same binary while at least 4 of them that I'm aware of provide different extensions and features... how should such stuff be named by distribution packagers in a sane way while still preserving sane UX for the end-user?
There are also other kind of conflicting names of re-implementations that are not compatible to each other but having other programs depending on them. They create lot of unnecessary maintenance and UX overhead on a distribution level to patch all the things depending on one or the other while such situations can just easily be avoided.
Nothing of this is something you **need** to care about considering a boxed point of view just for this project. But it's certainly something that _could_ be taken into account and as I'm someone being involved in a lot of distribution related work I always try to actually solve such situations "sanely" on a lower level (the upstream) before somehow dealing with a "fuckup" situation and make it work somehow with the real world around it. Honestly, you are totally free to ignore this point of view while just taking your projects scope into account. That's why I started this long explanation that (after this statement) I'm done with trying to convince you or argue further. I won't be upset, angry or anything else, its **really** just that I first try to solve such situations by avoiding them (which, in my personal opinion, is a lot cleaner solution).

Cheers and have a nice day :smiley_cat:

**Comment by lantw44** [comment]
> To clarify: That the Arch-provided a pwntools package (https://aur.archlinux.org/packages/python2-pwntools/) which contains a command which conflicts with a different Arch-provided package, is not a pwntools problem.

This package already renames all pwntools-provided commands to `pwn-*` to avoid conflicts. It was not done before this issue was opened because we think it is better to fix it upstream first. If upstream refuses to make the change, we can keep the renaming script downstream as long as the renaming doesn't break any functionality.

> That's an issue for the distro to resolve. It's specifically why the `update-alternatives` command exists on Debian-based distributions.

I don't think `update-alternatives` is able to fully resolve conflicts between commands that do completely different things or have completely different interfaces.

From the man page of `update-alternatives`:

> It is possible for several programs fulfilling the same or similar functions to be installed on a single system at the same time. For example, many systems have several text editors installed at once.
This gives choice to the users of a system, allowing each to use a different editor, if desired, but makes it difficult for a program to make a good choice for an editor to invoke if the user has not specified a particular preference.

All text editors support a simple interface (`text-editor-command file-to-be-edited`) and do exactly the one thing (open `file-to-be-edited` for an user to edit it) , so users can easily change the default editor without breaking existing programs or scripts. However, this doesn't apply to the conflict between `ax25-node` and `nodejs`, or conflict between `checksec.sh` and `pwntools`. `ax25-node` and `nodejs` do completely different things, and  `checksec.sh` and `pwntools` have incompatible command-line interfaces. The syntax of `checksec.sh` is `checksec --file elf-file`, but `pwntools` only supports `checksec elf-file`. This means that changing the implementation of `checksec` command is not easy even if we have an `update-alternatives`-like system. Existing programs and scripts have to be modified to adapt to the change.

I think changing the symlink between incompatible implementations of `checksec` is not a big issue because `checksec` is not widely used in scripts, but it is really not what can be fully resolved by using `update-alternatives`.

**Comment by Idolf** [comment]
Let me try to summarize this discussion as I understand it.

### The facts
- A tool exists called checksec.sh. It is broken and unmaintained.
- We provide a tool with the same features (and more). It is called checksec.
- At some point Arch Linux decided to rename checksec.sh to checksec.
- This introduces a name collision.

### Potential solutions
1. Stop renaming the original tool
2. Rename the original tool to something else, such as `checksec-ancient`
3. Use update-alternatives
4. Introduce meta-data to specify that the two packages are mutually exclusive
5. Rename checksec in our repo

### Your arguments

- You don't want 1-4 because you are of the opinion that checksec.sh owns the name checksec for moral reasons.
- You also don't want 1-4, because people might still be using the original tool.
- You additionally don't want 3), because we are not shell-script-compatible.
- You don't want 5, because it is more work for you.

Feel free to correct me if I am misrepresenting you or you want to add additional arguments to the list.

### My point-for-point counter arguments

- I disagree with your moral point of view. If it was a very unique name, then maybe, however the tool does exactly what the name says it does.
- I don't care if people are still using the tool. It is broken, they should stop.
- I would be okay with making a reasonable effort into becoming shell-script-compatible, if that was what allowed us to move forward.
- This is of course unfortunate, however this is an issue that only affects Arch Linux, because of a decision made specifically for Arch Linux, and the work has already been done.

### Conclusion

Unless I have missed one of your arguments, it seems that we simply will not agree on this issue. If you feel that I have misrepresented your opinion or left out arguments, feel free to add them, and I will re-open the issue and update my post.

Also feel free to let us know, if you want to go with solution 3). Otherwise I will consider this issue closed.

**Comment by anthraxx** [comment]
still wondering why everybody is always talking about "Arch Linux only" when this clearly is the same for Fedora, Void Linux, Gentoo, CentOS  and possibly others (just searched for like 5 min and it is the case exactly because of the sane reasons I already explained above).
Also I won't explain my other arguments again exactly because of the reasons I provided above, if you are interested in that argumentation then simply read my text again -- especially the sslscan example part (because in fact it is the same for checksec as you are not the first people having the idea to replace it with the same name) ¯\_(ツ)_/¯

**Comment by Idolf** [comment]
I agree, this does not appear to be Arch Linux only. This changes the situation slightly, however not enough.

It think it is completely fair, that you do not wish to re-summarize your arguments. I also think it is fair, that I will not comb through your wall-of-text for any arguments I might have missed. It is somewhat painful to read through it, since it contains no formatting and too little punctuation.

Feel free to let us know if you want to go with model 3 or if you change your mind and want to summarize any arguments you think I have missed.

**Comment by zachriggle** [comment]
@anthraxx if we used the common entry point `pwn` for all of our commands (e.g. `pwn asm` and `pwn checksec`), would this resolve the problem.  Specifically, are there any other packages which already expose a `pwn` binary?

**Comment by anthraxx** [comment]
@zachriggle did not find any 'pwn' in /usr/bin/ in the whole respository so I guess that should work. This would also provide a consistent user experience whatever distro the user may use :+1: 
Of cause this would "require" that the tools are not directly distributed anymore to /usr/bin... but your referenced ticket #660 states exactly this! :smile_cat: *happy*
