### ISSUE TITLE
Logging goes to `sys.stdout`

### ISSUE THREAD

**Issue by br0ns** [Gallopsled/pwntools#759]
In the documentation for `log.Handler` (http://pwntools.readthedocs.io/en/stable/log.html#pwnlib.log.Handler) it says that output goes to `sys.stderr`.  There are two problems with that:
1. It does not.  I goes to `sys.stdout` (https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/log.py#L655)
2. Where the output goes is not controlled by `log.Handler`

I propose two changes:
1. Send output to `sys.stderr`
2. Change the documentation so that `sys.stderr`/`sys.stdout` is not mentioned in `log.Handler` but rather in `log.install_default_handler` or maybe just `log`

**Comment by zachriggle** [comment]
Yeah, it looks like some of the logging documentation is wrong in a few places, or in the wrong location.

For the standard everything-and-the-kitchen-sink exploit scenario (`from pwn import *`), stdout seems correct since the "log output" is generally the _only_ or _primary_ output of the exploit script.  Python exceptions / tracebacks (including via `log.error()`) go to stderr, which again I think is the correct behavior.

``` sh
$ python -c 'from pwn import *; log.error("message")' 2>/dev/null
[ERROR] message

$ python -c 'from pwn import *; log.error("message")' 1> /dev/null
  File "<string>", line 1, in <module>
  File "/Users/riggle/pwntools/pwnlib/log.py", line 414, in error
    raise PwnlibException(message % args)
pwnlib.exception.PwnlibException: message
```

Users who wish to change this behavior can update `pwnlib.log.console.stream` at runtime, which should perhaps be documented, or exposed via some other mechanism (sticking it in e.g. `context.log_XXX` seems like the best bet, alongside `log_level` and `log_file`).  There's also the standard `logging` mechanism for changing where things go.

It might also make sense to add a `pwnlib.args` magic argument for this, e.g. `export PWNLIB_LOG_STDERR` so that users can just set it in their e.g. `~/.bashrc` files to have that behavior.  I think this is a useful middle ground that will achieve the behavior @br0ns suggested.  This would be easier than adding it to `context`.

For library use (`import pwnlib`), `stderr` is likely appropriate, but we don't set up any log handlers at all in that scenario. Because `import pwnlib` doesn't invoke `install_default_handler`, by default it goes nowhere until logging is configured.  I think the current behavior here is correct (do nothing, it's a library).

``` py
import pwnlib
pwnlib.tubes.process.process(['echo', 'hello']).recvall()
# No output
```

However, exceptions which are raised (including via `log.error`) do get raised as normal exceptions, which are printed on `stderr` by default (per normal in Python) even in library mode.

**Comment by zachriggle** [comment]
Also, it appears we already set logs to go to `stderr` for the command-line utilities, which produce other output on `stdout`, for easy piping: 
https://github.com/Gallopsled/pwntools/blob/913a3eba9ea92aa55efadb7bd9dd6e7db70802ac/pwnlib/commandline/common.py#L8

**Comment by zachriggle** [comment]
Implementation added, `export PWNLIB_STDERR=1` will now cause logging to go to `stderr` by default.
