### ISSUE TITLE
autobaud support for pwnlib.tubes.serialtube

### ISSUE THREAD

**Issue by lucasduffey** [Gallopsled/pwntools#763]
would be nice feature

**Comment by zachriggle** [comment]
My understanding is that this is no more possible for `pwntools` than it is for e.g. `screen` or `minicom`.

Could you please elaborate?

**Comment by lucasduffey** [comment]
this is a good example: https://github.com/devttys0/baudrate/blob/master/baudrate.py

it wouldn't be 100% perfect - but you can still have a degree of accuracy for some serial devices

**Comment by zachriggle** [comment]
That requires data to be flowing over the serial cable, and is destructive to the data (i.e. data received while at the wrong baudrate is effectively destroyed).

This might be useful for a stand-alone utility or something in `pwnlib.commandline` but otherwise doesn't seem useful as a function of the `serialtube` itself.

**Comment by zachriggle** [comment]
It also looks like @devttys0's `baudrate` tool is a stand-alone, MIT-licensed script.  I'm not sure we could add anything to it functionally, outside of outright including it.  That doesn't add anything except for reducing the number of packages to install.

**Comment by lucasduffey** [comment]
if you start at a high enough baudrate you could potentially preserve all the data. This does seem like this might be out of project scope for now.
