### ISSUE TITLE
MIPS shellcode contains null bytes

### ISSUE THREAD

**Issue by RobertLarsen** [Gallopsled/pwntools#807]
It didn't always do that. I have built a docker image containing the latest version of pwntools and also one containing the a69dc3e commit (the last mips commit from me). These are the results:

```
$ docker run --rm robertlarsen/pwntools:latest shellcraft mips.linux.sh | xxd
00000000: 7368 0934 fcff a9af fcff bd27 ffff 0628  sh.4.......'...(
00000010: fcff a6af fcff bd23 fbff 1924 2730 2003  .......#...$'0 .
00000020: 2030 dd00 fcff a6af fcff bd23 2030 a003   0.........# 0..
00000030: fcff a0af fcff bd27 ffff 0528 fcff a5af  .......'...(....
00000040: fcff bd23 2028 a003 6269 093c 2f2f 2935  ...# (..bi.<//)5
00000050: f4ff a9af 7368 093c 6e2f 2935 f8ff a9af  ....sh.<n/)5....
00000060: fcff a0af f4ff bd27 2020 a003 ab0f 0234  .......'  .....4
00000070: 2630 c500 2628 c500 2630 c500 0c01 0101  &0..&(..&0......
$ docker run --rm robertlarsen/pwntools:a69dc3e shellcraft mips.linux.sh | xxd
00000000: 0101 0134 6901 2138 fcff a1a7 2f73 0134  ...4i.!8..../s.4
00000010: feff a1a7 fcff a18f fcff a1af fcff bd23  ...............#
00000020: 696e 013c 2f62 2134 fcff a1af fcff bd23  in.</b!4.......#
00000030: f8ff bdaf ffff 0628 fcff a6af f8ff a48f  .......(........
00000040: f8ff bd23 fcff bdaf fcff a58f ab0f 0234  ...#...........4
00000050: 0c09 0901                                ....
```

Also, the `mips.linux.sh` shellcode has grown from 84 bytes to 128 bytes.

**Comment by zachriggle** [comment]
This was done to fix the busybox/android/whatever issue where sh is
retarded and segfaults if argc==0.



On Tue, Dec 6, 2016 at 5:02 AM Robert Larsen <notifications@github.com>
wrote:

It didn't always do that. I have built a docker image containing the latest
version of pwntools and also one containing the a69dc3e
<https://github.com/Gallopsled/pwntools/commit/a69dc3ebc6872c37d05c9a1337c8950c70d4e6ce>
commit (the last mips commit from me). These are the results:

$ docker run --rm robertlarsen/pwntools:latest shellcraft mips.linux.sh | xxd
00000000: 7368 0934 fcff a9af fcff bd27 ffff 0628  sh.4.......'...(
00000010: fcff a6af fcff bd23 fbff 1924 2730 2003  .......#...$'0 .
00000020: 2030 dd00 fcff a6af fcff bd23 2030 a003   0.........# 0..
00000030: fcff a0af fcff bd27 ffff 0528 fcff a5af  .......'...(....
00000040: fcff bd23 2028 a003 6269 093c 2f2f 2935  ...# (..bi.<//)5
00000050: f4ff a9af 7368 093c 6e2f 2935 f8ff a9af  ....sh.<n/)5....
00000060: fcff a0af f4ff bd27 2020 a003 ab0f 0234  .......'  .....4
00000070: 2630 c500 2628 c500 2630 c500 0c01 0101  &0..&(..&0......
$ docker run --rm robertlarsen/pwntools:a69dc3e shellcraft mips.linux.sh | xxd
00000000: 0101 0134 6901 2138 fcff a1a7 2f73 0134  ...4i.!8..../s.4
00000010: feff a1a7 fcff a18f fcff a1af fcff bd23  ...............#
00000020: 696e 013c 2f62 2134 fcff a1af fcff bd23  in.</b!4.......#
00000030: f8ff bdaf ffff 0628 fcff a6af f8ff a48f  .......(........
00000040: f8ff bd23 fcff bdaf fcff a58f ab0f 0234  ...#...........4
00000050: 0c09 0901                                ....

Also, the mips.linux.sh shellcode has grown from 84 bytes to 128 bytes.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Gallopsled/pwntools/issues/807>, or mute the thread

**Comment by zachriggle** [comment]
This was done to fix the busybox/android/whatever issue where sh is retarded and segfaults if argc==0.

See #626, #692, and #693

If brevity and NULL-free matters, use this instead:

```
~ ❯❯❯ pwn shellcraft mips.linux.execve /bin/sh  | xxd
0000000: 6269 093c 2f2f 2935 f4ff a9af 7368 093c  bi.<//)5....sh.<
0000010: 6e2f 2935 f8ff a9af fcff a0af f4ff bd27  n/)5...........'
0000020: 2020 a003 ffff 0528 ffff 0628 ab0f 0234    .....(...(...4
0000030: 0c01 0101                                ....
```

Otherwise, I'll leave this up to @Idolf to decide on (per https://github.com/Gallopsled/pwntools/issues/626#issuecomment-240806020).
