### ISSUE TITLE
Waiting for debugger when attaching to gdb splitting terminal via pwn.dbg.attach

### ISSUE THREAD

**Issue by ulexec** [Gallopsled/pwntools#819]
Hi. Im on Ubuntu 16.04 64 bits. I intalled the latest version of pwntools. When I try to split a terminal and attach a process with gdb via pwn.gdb.attach(), the screen gets splitted but gdb fails to attach and the script just waits infinitely for gdb. Below is a screenshot of the output im getting:

```
[+] Starting local process './D-CTFQuals_WarmHeap100.bin': Done
[*] running in new terminal: gdb -q  "/home/remnux/CTFs/D-CTF/D-CTFQuals_WarmHeap100.bin" 2872
[↑] Waiting for debugger
```

A Poc of the code im using is the following:

```py
#!/usr/bin/env/python2
import pwn

pwn.context(terminal = ['xterm', 'splitw'])

exit_got = 0x601068
flag = 0x400826

gdb_cmd = []
gdb_cmd.append('c')
gdb_cmd = '\n'.join(gdb_cmd)

r = pwn.process('./D-CTFQuals_WarmHeap100.bin')
pwn.gdb.attach(r, execute=gdb_cmd)
r.sendline('A'*40 + pwn.p64(exit_got))
r.sendline(pwn.p64(flag))
print r.recvall()
```

Is this behavior normal or am I missing something?
Regards

**Comment by zachriggle** [comment]
xterm does not support "splitw". I expect this is your issue.

Two suggestions:

1.) Remove your context.term statement entirely, or ensure
run_in_new_terminal works for any command at all.
2.) Multiline strings are easier than what you're doing to pass gdb_cmd. In
your case, you can just pass e.g. "continue".

**Comment by ulexec** [comment]
The problem is gdb not connecting, rather than the window not spitting. Ive tried this with tmux and I have the same problem

**Comment by zachriggle** [comment]
Sounds like your GDB is broken.  I recommend following the [ISSUE TEMPLATE](https://github.com/Gallopsled/pwntools/blob/dev/.github/ISSUE_TEMPLATE.md).

**Comment by zachriggle** [comment]
Verified that this is working correctly for me

**Comment by l-maia** [comment]
@zachriggle 
I just reproduced this problem. 

Launching a terminal by hand i noticed that it was sending  a message to stderr .
The function run_in_new_terminal has a **os.close(2)** which will hang the exec when the terminal outputs stuff (like QDBusConnection log messages on KDE which should be non-blocking). 

Commenting this line will fix this for me, but i think the proper patch would be to wrap the output to the log facility and not simply closing it.

**Comment by zachriggle** [comment]
What OS / environment / version?

**Comment by l-maia** [comment]
Debian Jessie running KDE. 

If you use Gnome there's no problem because there's no output from the terminal command.

**Comment by Mosk0ng** [comment]
I just got this problem, and refered to the docment.
______
Kernel Yama ptrace_scope

The Linux kernel v3.4 introduced a security mechanism called ptrace_scope, which is intended to prevent processes from debugging eachother unless there is a direct parent-child relationship.

This causes some issues with the normal Pwntools workflow, since the process heirarchy looks like this:

python ---> target
       `--> gdb

Note that python is the parent of target, not gdb.

In order to avoid this being a problem, Pwntools uses the function prctl(PR_SET_PTRACER, PR_SET_PTRACER_ANY). This disables Yama for any processes launched by Pwntools via process or via ssh.process().

Older versions of Pwntools did not perform the prctl step, and required that the Yama security feature was disabled systemwide, which requires root access.

___

It seems there is something to do with the problem, and I will try to get a lower version of Unbuntu

**Comment by 9iang22** [comment]
记下这个程序的pid然后
再打开一个终端，然后打开gdb
键入
attach pid
stop
b xxxxx  #设置断点
c
就可以了
