### ISSUE TITLE
context not updating properly for asm

### ISSUE THREAD

**Issue by bannsec** [Gallopsled/pwntools#926]
When switching context using `asm` i've noticed it has problems updating.

This works:
```python
In [1]: from pwn import *

In [2]: context(arch='i386')

In [3]: asm(shellcraft.sh())
Out[3]: 'h\x01\x01\x01\x01\x814$ri\x01\x011\xd2Rj\x04Z\x01\xe2R\x89\xe2jhh///sh/binj\x0bX\x89\xe3\x89\xd1\x99\xcd\x80'
```

This does not:
```python
In [1]: from pwn import *

In [2]: context(arch='amd64')

In [3]: asm(shellcraft.sh())
Out[3]: 'hri\x01\x01\x814$\x01\x01\x01\x011\xd2Rj\x08ZH\x01\xe2RH\x89\xe2jhH\xb8/bin///sPj;XH\x89\xe7H\x89\xd6\x99\x0f\x05'

In [4]: context(arch='i386')

In [5]: asm(shellcraft.sh())
[ERROR] There was an error running ['/usr/bin/x86_64-linux-gnu-as', '-64', '-o', '/tmp/pwn-asm-VpZzIm/step2', '/tmp/pwn-asm-VpZzIm/step1']:
    It had the exitcode 1.
    It had this on stdout:
    /tmp/pwn-asm-VpZzIm/step1: Assembler messages:
    /tmp/pwn-asm-VpZzIm/step1:12: Error: operand type mismatch for `push'
    /tmp/pwn-asm-VpZzIm/step1:14: Error: operand type mismatch for `pop'
    /tmp/pwn-asm-VpZzIm/step1:16: Error: operand type mismatch for `push'
    /tmp/pwn-asm-VpZzIm/step1:24: Error: operand type mismatch for `pop'
```

In the later, it looks like the assembling command is not changed to i386 context.

**Comment by zachriggle** [comment]
Per the docs for [`ContextType.arch`](http://docs.pwntools.com/en/stable/context.html#pwnlib.context.ContextType.arch):

> If an architecture is specified which also implies additional attributes (e.g. ‘amd64’ implies 64-bit words, ‘powerpc’ implies big-endian), these attributes will be set on the context if a user has not already set a value.

```py
>>> context
ContextType()
>>> context.arch = 'amd64'
>>> context
ContextType(arch = 'amd64', bits = 64, endian = 'little')
>>> context.arch = 'i386'
>>> context
ContextType(arch = 'i386', bits = 64, endian = 'little')
```

The GNU assembler is expecting 64-bit Intel instructions (`'/usr/bin/x86_64-linux-gnu-as', '-64' ...`), you're providing it with `i386` instructions.  If you wish to change the architecture back to 32-bit, you **MUST** either clear the context:

```py
>>> context.clear()
>>> context.arch = 'i386'
# Alternately
>>> context.clear(arch = 'i386')
```

Or you must explicitly set the bit-width values.  

```py
>>> context.arch = 'i386'
>>> context.bits = 32
# Alternately
>>> context.update(arch = 'i386', bits = 32)
```

Setting the bits is only done as a convenience.  Since you are not specifying `bits`, and `bits` has already been set (to `64`), it is not modified.

`i386-64` is not a supported configuration.

**Comment by zachriggle** [comment]
Also, TYRM (Today You Reminded Me) that I had aliased `__call__` to `update()` for `ContextType`.  Neat!
