### ISSUE TITLE
Documentation: pwnlib.dynelf example should use p.leak and not p.read

### ISSUE THREAD

**Issue by mkravchik** [Gallopsled/pwntools#930]
Hi,
In the example code at for [dynelf](http://docs.pwntools.com/en/stable/dynelf.html?highlight=dynelf) it uses p.read to read process memory. 

> p = process('./pwnme')
> ...
> def leak(address):
>     data = p.read(address, 4)
>     log.debug("%#x => %s" % (address, (data or '').encode('hex')))
>     return data

This looks like an error to me, it should be **p.leak** instead.

**Comment by zachriggle** [comment]
Kind of, I can see the confusion.

The intent of the example is to "assume" that we have some process where we can leak data via some mechanism.  In the example, we just use `p.read`, where `p` is a `process` object.

The example isn't "complete" since we'd have to package a binary and make the example more complex.  It's intended just to show the **general idea** of how to use `DynELF` in normal usage.

Separately, `process` objects do have a `.leak` member, which does actually read memory directly from the process via `/proc/xxx/mem`.  While this would make the example function, it would defeat the purpose of showing how it's *actually* used against real challenges -- generally, the leak comes across the wire, and we don't have access to `/proc/xxx/mem`.

**Comment by zachriggle** [comment]
Closing this in favor of #931 for tracking.
