### ISSUE TITLE
Generic function to get section offset

### ISSUE THREAD

**Issue by Need-To-Learn** [Gallopsled/pwntools#934]
I looked at the doc and the source code and I didn't find any functions which can return any section's offset quickly.

For instance, if I want to get the '.got.plt' section I have to do : 
```
libc.get_section_by_name('.got.plt').header.sh_addr
```

I think that it should be an interesting feature to implement.

**Comment by zachriggle** [comment]
Normally, I'm one to add features (because LOC are cheap), but in this case I'm not sure there's really a "better" way to do it.  The difference would just be a different function name, and a few characters saved.  I think that `get_section_by_name` is sufficiently generic to get at what people want, and has a standardized interface (via `pyelftools`).  

Adding individual-header-field-accessor-methods-for-named-sections just seems a bit too specialized.  Why not add functions for the `vaddr` and `memsz` and `filesz` also?  You can see how this might get bloated.

I'll reopen this if others want the feature or disagree.

**Comment by zachriggle** [comment]
As a side-note, I think a better way to do this would be to submit an upstream patch to `pyelftools` which accesses `self.header` fields via `__getattribute__`.  This would strip a the `.header` bit, and make your example slightly shorter.
